Add NewRP
LabyMod/server-media pull request #1000
Opened 2024-03-03 22:09 UTC by RealBenluka

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-03-03 22:51 UTC, maaaathis requested changes

2024-03-03 22:51 UTC, maaaathis commented on minecraft_servers/newrp/manifest.json
> +    "web": "https://newrp.de",
No real content; it's only the plesk default page

2024-03-03 22:51 UTC, maaaathis commented on minecraft_servers/newrp/manifest.json
> +    "web_shop": "https://shop.newrp.de",
No content; it's only the plesk login page

2024-03-03 22:51 UTC, maaaathis commented on minecraft_servers/newrp/background.png
Compress this file

2024-03-03 22:51 UTC, maaaathis commented on minecraft_servers/newrp/background@2x.png
Compress this file

2024-03-04 13:27 UTC, DoJapHD commented
Server not released yet; reopen PR once server is released

2024-03-04 13:27 UTC, closed without merging