Add VinixMC.net
LabyMod/server-media pull request #1031
Opened 2024-03-26 10:40 UTC by vinixmc

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-03-26 13:48 UTC, maaaathis requested changes

2024-03-26 13:48 UTC, maaaathis commented on minecraft_servers/vinixmc/manifest.json
> +    "discord": "https://discord.vinixmc.net"
Custom links are reserved for partners only; use a normal discord.gg/[INVITE] link instead

2024-03-26 13:48 UTC, maaaathis commented on minecraft_servers/vinixmc/manifest.json
> +    "%.vinixmc.net"
Doesn't look like a real wildcard
![image](https://github.com/LabyMod/server-media/assets/37186532/f92afb3c-99bf-4050-a17c-a603c50a20a4)

2024-03-26 13:48 UTC, maaaathis commented on minecraft_servers/vinixmc/manifest.json
> +    "twitter": "16a2",
References not to a Minecraft server. Are you sure about that?

2024-03-26 20:21 UTC, vinixmc commented
Everything now is good, is a server wildcard required?

2024-03-26 22:21 UTC, maaaathis commented
> Everything now is good, is a server wildcard required?

Nope, it's not required.

2024-03-27 01:16 UTC, vinixmc commented
> > Everything now is good, is a server wildcard required?
> 
> Nope, it's not required.

How much does it take to verify?

2024-04-02 11:27 UTC, vinixmc commented
> > Everything now is good, is a server wildcard required?
> 
> Nope, it's not required.


> > Everything now is good, is a server wildcard required?
> 
> Nope, it's not required.

What happened? when the server will be added?

2024-04-02 16:37 UTC, vinixmc commented
> > > > Everything now is good, is a server wildcard required?
> > 
> > 
> > > 
> > 
> > 
> > > Nope, it's not required.
> > 
> > 
> > What happened? when the server will be added?
> 
> You need to remove the wildcard, if it's not a real wildcard.

I have removed the wildcard

2024-04-02 21:56 UTC, vinixmc commented
> * JSON is invalid! Workflow is not able to check minecraft_servers/vinixmc/manifest.json
> 
> Please fix the issues by pushing **one** commit to the pull request to prevent too many automatic reviews.

2024-04-03 13:05 UTC, DoJapHD approved these changes

2024-04-03 13:06 UTC, merged