Update missing/wrong information
LabyMod/server-media pull request #1040
Opened 2024-03-31 14:36 UTC by Ente3

## Type of change

- [ ] Add new directory for a server
- [X] Update directory of a server
- [ ] Remove directory of a server
- [X] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-03-31 14:45 UTC, maaaathis requested changes

2024-03-31 14:45 UTC, maaaathis commented on minecraft_servers/baxnetzwerk/manifest.json
> +    "direct_ip": "play-bax.de"
```suggestion
    "direct_ip": "play-bax.de",
```

2024-03-31 14:47 UTC, maaaathis commented
You don't need to open a new PR everytime btw.

2024-03-31 16:35 UTC, Ente3 commented
Oh okay, I committed suggested changes

2024-03-31 16:59 UTC, maaaathis requested changes
sry, missed that before

2024-03-31 16:59 UTC, maaaathis commented on minecraft_servers/baxnetzwerk/manifest.json
> +    "server_name": "BaxNetzwerk",
```suggestion
    "server_name": "baxnetzwerk",
```

2024-03-31 17:06 UTC, Ente3 commented
Okay, everything resolved. Autocheck passes ^^

2024-03-31 18:33 UTC, maaaathis approved these changes
lgtm

2024-04-01 21:29 UTC, Ente3 commented
Hi, how to merge do master?
Merging still blocked

2024-04-02 18:17 UTC, merged