Removed network and adding network
LabyMod/server-media pull request #1046
Opened 2024-04-03 17:21 UTC by ezTxmMC

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-04-03 17:48 UTC, maaaathis requested changes

2024-04-03 17:48 UTC, maaaathis commented on minecraft_servers/laturia/manifest.json
> +      "team.laturia.net"
These are not real wildcards

2024-04-07 00:35 UTC, DoJapHD commented
Server not yet released; reopen PR once server is public

2024-04-07 00:35 UTC, closed without merging

2024-04-07 09:05 UTC, ezTxmMC commented
For pull #621 the server was also not public and was accepted