Update minicraftcz
LabyMod/server-media pull request #1047
Opened 2024-04-04 19:48 UTC by TestrGames

## Type of change

- [ ] Add new directory for a server
- [x ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x ] I have created the manifest.json with the required values

## Further comments

2024-04-05 05:43 UTC, maaaathis requested changes

2024-04-05 05:43 UTC, maaaathis commented on minecraft_servers/minicraftcz/manifest.json
> +      "web_support": "https://www.minicraft.cz/forum",
`web_support` cannot be a forum; use a faq or contact page instead

2024-04-05 05:43 UTC, maaaathis commented on minecraft_servers/minicraftcz/manifest.json
> +        "name": "Survival",
Key and name doesn't match

2024-04-05 05:43 UTC, maaaathis commented on minecraft_servers/minicraftcz/manifest.json
> +        "name": "OneBlock",
Key and name doesn't match

2024-04-05 05:43 UTC, maaaathis commented on minecraft_servers/minicraftcz/manifest.json
> +        "name": "SkyBlock",
Key and name doesn't match

2024-04-07 00:36 UTC, DoJapHD commented
Server is offline; Reopen PR once server is back online

2024-04-07 00:36 UTC, closed without merging

2024-04-07 08:24 UTC, TestrGames commented
hello, the server is not offline. We operate only in the Czech Republic and Slovakia. We have therefore blocked any access from the USA and similar countries to the server, it makes no sense for us to allow it.