Create manifest.json
LabyMod/server-media pull request #1054
Opened 2024-04-10 16:32 UTC by getSono

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-04-11 13:29 UTC, DinoMarlir requested changes
There is one bracket missing. Please update your manifest.

2024-04-11 13:32 UTC, getSono commented
> There is one bracket missing. Please update your manifest. 

What bracket?

2024-04-11 13:37 UTC, getSono commented
How I do that?
I’m currently on the iPad.

2024-04-11 13:43 UTC, getSono commented
And how can I add the } on Web Version? I'm new on GitHub

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Marlon ***@***.***>
Gesendet: Donnerstag, April 11, 2024 3:41 PM
An: LabyMod/server-media ***@***.***>
Cc: Sono ***@***.***>; Author ***@***.***>
Betreff: Re: [LabyMod/server-media] Create manifest.json (PR #1054)


Just write } at the bottom.

These resources may help you for the future:

  *   https://jsonlint.com/
  *   https://www.w3schools.com/js/js_json_syntax.asp

—
Reply to this email directly, view it on GitHub<https://github.com/LabyMod/server-media/pull/1054#issuecomment-2049722357>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3PGHIVYXJ32RFYT7EASHOTY42HKJAVCNFSM6AAAAABGAY26XCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBZG4ZDEMZVG4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-11 13:44 UTC, DinoMarlir commented
Yeah. Also you have to provide a icon file.

2024-04-11 13:54 UTC, getSono commented
I add the } and add icon.png @DinoMarlir

2024-04-11 13:56 UTC, DinoMarlir commented
There are some more errors. Please fix these. 

![Screenshot_20240411_155526.jpg](https://github.com/LabyMod/server-media/assets/72864666/9a6824e2-4d5e-42da-9a07-9f773e8e6157)

2024-04-11 13:58 UTC, DinoMarlir commented
Your icon is invalid too. Please read the documentation and the instructions in the wiki before you push something.

2024-04-11 14:03 UTC, DinoMarlir commented
Still invalid. Seems like you don't have much knowledge with Json. I would recommend you to learn the JSON syntax. Then you can push your fix.

2024-04-11 14:06 UTC, getSono commented
Yes, I usually never programming with JSON. (lol)
I don't need json in my Java, HTML or Python Projects.

Message ID: ***@***.***>

2024-04-11 19:50 UTC, maaaathis requested changes

2024-04-11 19:50 UTC, maaaathis commented on minecraft_servers/teamfive/manifest.json
> +    }
```suggestion
    ],
```

2024-04-11 19:50 UTC, maaaathis commented on minecraft_servers/teamfive/manifest.json
> +  }
```suggestion
```

2024-04-11 19:50 UTC, maaaathis commented on minecraft_servers/teamfive/manifest.json
> +        "name": "Citybulid",
```suggestion
      "citybuild": {
        "name": "Citybuild", 
```

2024-04-11 19:52 UTC, maaaathis requested changes
icon@2x.png is not given, but it is required.

2024-04-11 19:52 UTC, maaaathis commented on minecraft_servers/teamfive/icon.png
Invalid icon size! Size is 500x500px, must be 256x256px

2024-04-21 18:32 UTC, DoJapHD commented
The server is just a plain vanilla server?

2024-04-21 21:18 UTC, getSono commented
@DoJapHD No, But I currently reinstall the server

2024-04-21 21:27 UTC, DoJapHD commented
Reopen PR once server is ready and released

2024-04-21 21:27 UTC, closed without merging