added gamerherz
LabyMod/server-media pull request #1057
Opened 2024-04-12 19:40 UTC by Nicouschulas

## Type of change

- [x ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ x] I have created the manifest.json with the required values

## Further comments

2024-04-12 22:46 UTC, maaaathis requested changes

2024-04-12 22:46 UTC, maaaathis commented on minecraft_servers/gamerherz/background.png
Compress this file.

2024-04-12 22:46 UTC, maaaathis commented on minecraft_servers/gamerherz/background@2x.png
Compress this file.

2024-04-12 22:46 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +    "%.gamerherz.eu"
Doesn't look like a real wildcard
![image](https://github.com/LabyMod/server-media/assets/37186532/833d2603-7c26-4d7d-a7db-ce8e45b9ea4a)

2024-04-12 22:46 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +      "name": "Schach",
Key doesn't match name

2024-04-12 22:46 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +      "name": "Duels 1.8",
Key doesn't match name

2024-04-12 22:46 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +    "web": "https://www.gamerherz.eu/",
Had no real content:
![image](https://github.com/LabyMod/server-media/assets/37186532/4111eab4-41d9-405d-a900-0c9df8be336a)

2024-04-14 09:43 UTC, maaaathis requested changes

2024-04-14 09:43 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +    "web": "https://gamerherz.eu",
No valid content

2024-04-14 09:43 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +    "web_support": "https://gamerherz.eu/contact.html
```suggestion
    "web_support": "https://gamerherz.eu/contact.html",
```

2024-04-14 09:43 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +
```suggestion
```

2024-04-18 17:11 UTC, maaaathis requested changes

2024-04-18 17:11 UTC, maaaathis commented on minecraft_servers/gamerherz/background.png
Compress this file

2024-04-18 17:11 UTC, maaaathis commented on minecraft_servers/gamerherz/background@2x.png
Compress this file

2024-04-18 17:11 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +
```suggestion
```

2024-04-20 15:14 UTC, maaaathis requested changes

2024-04-20 15:14 UTC, maaaathis commented on minecraft_servers/gamerherz/manifest.json
> +  "direct_ip": "Gamerherz.eu"
```suggestion
  "direct_ip": "gamerherz.eu",
```

2024-04-20 15:14 UTC, maaaathis commented on minecraft_servers/gamerherz/background.png
Compress this file.

2024-04-20 15:14 UTC, maaaathis commented on minecraft_servers/gamerherz/background@2x.png
Compress this file.

2024-04-21 18:34 UTC, DoJapHD requested changes

2024-04-21 18:34 UTC, DoJapHD commented on minecraft_servers/gamerherz/background.png
Compress

2024-04-21 18:34 UTC, DoJapHD commented on minecraft_servers/gamerherz/background@2x.png
Compress

2024-04-22 16:56 UTC, closed without merging