Added LendMark
LabyMod/server-media pull request #106
Opened 2021-08-15 14:15 UTC by SlenkyDev

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2021-08-15 20:29 UTC, JakobBruening requested changes

2021-08-15 20:29 UTC, JakobBruening commented on minecraft_servers/lendmark/manifest.json
> +      "youtube": "https://www.youtube.com/channel/UC1Khdip7ObGGN4OCsuSlg0gt"
The link does not work.

2021-08-15 20:30 UTC, SlenkyDev commented on minecraft_servers/lendmark/manifest.json
> +      "youtube": "https://www.youtube.com/channel/UC1Khdip7ObGGN4OCsuSlg0gt"
Which link exactly?

2021-08-15 20:31 UTC, SlenkyDev commented on minecraft_servers/lendmark/manifest.json
> +      "youtube": "https://www.youtube.com/channel/UC1Khdip7ObGGN4OCsuSlg0gt"
got it

2021-08-15 21:08 UTC, JakobBruening approved these changes
Thank you!

2021-08-15 21:08 UTC, merged

2021-08-16 04:36 UTC, SlenkyDev commented
It looks like the images weren't updated

2021-08-16 09:35 UTC, JakobBruening commented
Hey @SlenkyDev!
The logo is shown correctly on the LABY.net server page. But for the background we request `background@2x.png`, that was not added with your Pull request.

BR, Jakob

2021-08-16 09:50 UTC, SlenkyDev commented
> Hey @SlenkyDev!
> The logo is shown correctly on the LABY.net server page. But for the background we request `background@2x.png`, that was not added with your Pull request.
> 
> BR, Jakob

Oh okay, can I open a second pull request to add it?

2021-08-16 09:58 UTC, JakobBruening commented
Of course you can do that! I'm looking forward seeing the PR!

2021-08-16 10:04 UTC, SlenkyDev commented
Okay, thanks!

2021-08-16 10:15 UTC, SlenkyDev commented
> Of course you can do that! I'm looking forward seeing the PR!

https://github.com/LabyMod/server-media/pull/107