Create mainfest.json
LabyMod/server-media pull request #1061
Opened 2024-04-14 21:33 UTC by Pikaswelt

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-04-15 06:19 UTC, maaaathis requested changes
You need at a least a `icon.png` and a `icon@2x.png`. See https://github.com/LabyMod/server-media/blob/master/docs/Files.md

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
Rename this file to `manifest.json`

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +  ],
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "web_shop": "-",
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "web_support": "https://web.crazymin.de/support",
Not reachable

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "twitter": "-",
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "tiktok": "-",
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "facebook": "-",
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "instagram": "-",
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "teamspeak": "-"
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +    "youtube": "https://www.youtube.com/@CrazyMineMC",
```suggestion
    "youtube": "https://www.youtube.com/@CrazyMineMC"
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +      "name": "Citybuild",
Key doesn't match to name

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +      "url": "https://web.crazymine.de/boxpvp",
Not found

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +      "url": "https://web.crazymine.de/citybuild",
Not found

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +  "user_stats": "https://laby.net/@{userName}",
```suggestion
```

2024-04-15 06:19 UTC, maaaathis commented on minecraft_servers/crazymine/mainfest.json
> +  "yt_trailer": "-",
```suggestion
```

2024-04-24 19:49 UTC, DoJapHD commented
Inactive

2024-04-24 19:49 UTC, closed without merging