added gamerherz
LabyMod/server-media pull request #1071
Opened 2024-04-23 14:26 UTC by Nicouschulas

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-04-26 09:11 UTC, DoJapHD requested changes

2024-04-26 13:28 UTC, Nicouschulas commented on minecraft_servers/gamerherz/background@2x.png
Yeah, but a there is a bug. I asked some others evertime we upload it the first time it is false comressd. Any idea how to fix this?

2024-04-26 20:28 UTC, DoJapHD requested changes

2024-04-26 20:28 UTC, DoJapHD commented on minecraft_servers/gamerherz/background.png
Still not compressed
Let's try this:
Remove the files completely with a commit and then readd the compressed files with a commit.

2024-04-26 20:28 UTC, DoJapHD commented on minecraft_servers/gamerherz/background@2x.png
Aswell

2024-04-27 12:32 UTC, Nicouschulas commented on minecraft_servers/gamerherz/background.png
ok I try this

2024-04-28 14:20 UTC, DoJapHD commented
Upload these two again
https://workupload.com/archive/nWmBh3FcAx

2024-04-29 13:28 UTC, Nicouschulas commented
> Upload these two again https://workupload.com/archive/nWmBh3FcAx

ok I try it

2024-04-29 16:30 UTC, DoJapHD approved these changes
There we go...

2024-04-29 16:30 UTC, merged

2024-04-30 13:43 UTC, Nicouschulas commented
> There we go...

Hmm strange. But thanks