ADD NoviaMC
LabyMod/server-media pull request #1076
Opened 2024-04-26 20:30 UTC by sudo-Tiger

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-04-27 16:17 UTC, sudo-Tiger commented
Server is Online

2024-04-28 19:11 UTC, DoJapHD requested changes

2024-04-28 20:30 UTC, sudo-Tiger commented on minecraft_servers/noviamc/manifest.json
> +    "%.noviamc.de"
I removed the %

2024-04-28 20:40 UTC, DoJapHD commented on minecraft_servers/noviamc/manifest.json
> +    "%.noviamc.de"
That's also not a wildcard...
Just remove it as a whole

2024-04-28 20:42 UTC, sudo-Tiger commented on minecraft_servers/noviamc/manifest.json
> +    "%.noviamc.de"
Removed

2024-04-29 12:12 UTC, DoJapHD approved these changes

2024-04-29 12:12 UTC, merged