Add MinecraftServer
LabyMod/server-media pull request #1094
Opened 2024-05-02 19:38 UTC by Elioxx

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-05-02 21:06 UTC, maaaathis requested changes

2024-05-02 21:06 UTC, maaaathis commented on minecraft_servers/minecraftserver/background.png
Compress this file.

2024-05-02 21:06 UTC, maaaathis commented on minecraft_servers/minecraftserver/background@2x.png
Compress this file.

2024-05-02 21:06 UTC, maaaathis commented on minecraft_servers/minecraftserver/manifest.json
> +
```suggestion
```

2024-05-03 04:38 UTC, DoJapHD approved these changes

2024-05-03 04:39 UTC, merged