Add Thorma90 Network
LabyMod/server-media pull request #1129
Opened 2024-05-27 16:17 UTC by EinfachFloTV

2024-05-27 18:45 UTC, DoJapHD requested changes

2024-05-27 18:45 UTC, DoJapHD commented on minecraft_servers/thorma90/background.png
Compress image

2024-05-27 18:45 UTC, DoJapHD commented on minecraft_servers/thorma90/background@2x.png
Compress image

2024-05-27 18:45 UTC, DoJapHD commented on minecraft_servers/thorma90/manifest.json
> +      "web": "https://thorma90.net",
https://i.imgur.com/RJgActK.png

2024-05-27 18:45 UTC, DoJapHD commented on minecraft_servers/thorma90/manifest.json
> +      "%.thorma90.net"
Not a real wildcard
https://i.imgur.com/cEteI6A.png

2024-05-27 19:00 UTC, EinfachFloTV commented
Updated

2024-05-28 09:52 UTC, DoJapHD approved these changes

2024-05-28 09:52 UTC, merged