Update primeblocks
LabyMod/server-media pull request #1134
Opened 2024-05-29 03:31 UTC by jvstinxz

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-05-29 09:52 UTC, DoJapHD approved these changes

2024-06-02 18:26 UTC, DoJapHD requested changes

2024-06-02 18:26 UTC, DoJapHD commented on minecraft_servers/primeblocks/manifest.json
> +      "tiktok": "ledevinreal"
Private account; either network or remove

2024-06-02 19:19 UTC, jvstinxz commented on minecraft_servers/primeblocks/manifest.json
> +      "tiktok": "ledevinreal"
fixed

2024-06-02 19:49 UTC, DoJapHD approved these changes

2024-06-02 19:49 UTC, merged