Update PrivatGames
LabyMod/server-media pull request #1153
Opened 2024-06-10 20:33 UTC by DavidFrings

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-06-10 20:59 UTC, DoJapHD requested changes

2024-06-10 20:59 UTC, DoJapHD commented on minecraft_servers/privatgames/manifest.json
> +    "project-3": {
If nonexistent yet, remove!

2024-06-10 20:59 UTC, DoJapHD commented on minecraft_servers/privatgames/manifest.json
Server is not reachable

2024-06-10 21:02 UTC, DavidFrings commented on minecraft_servers/privatgames/manifest.json
if you try to connect, with your client you can!

2024-06-10 21:22 UTC, DavidFrings commented
Online Prove:
https://imgur.com/vykUziJ

2024-06-10 21:25 UTC, DavidFrings commented
Mybe the bot has Problems because the server is ipv6 only .)

2024-06-10 21:36 UTC, DoJapHD commented
https://i.imgur.com/1G78wTe.png

2024-06-10 21:40 UTC, DavidFrings commented
ok, thats wierd. Do you have ipv6? or have you disabled cloudflare reverseproxys?

2024-06-10 22:07 UTC, DoJapHD commented
The domain has no entry linking to any Minecraft server. Are you sure that you didn't just mess with your hosts file?

2024-06-11 05:12 UTC, DavidFrings commented
Ok, I see that I have dns Issues. I am closing this pull request until i have fix all my issues and open a new request then. THX for your help :)

2024-06-11 05:12 UTC, closed without merging

2024-06-12 10:16 UTC, DavidFrings commented
I created an issue in Velocity, and they were able to help me fix my problem. My issue was that I had proxying activated in Cloudflare, but it should have been set to DNS only.

I'll make a new commit shortly. 

:)