NordicHub Update
LabyMod/server-media pull request #1157
Opened 2024-06-12 22:05 UTC by HxNoXi

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-06-12 22:11 UTC, HxNoXi reviewed
Don't know why it fails?

2024-06-12 22:30 UTC, DoJapHD requested changes

2024-06-12 22:30 UTC, DoJapHD commented on minecraft_servers/nordichub/manifest.json
> +      "web": "https://nordichub.dk",
Not reachable

2024-06-13 09:57 UTC, DoJapHD approved these changes

2024-06-13 09:57 UTC, merged