Update manifest.json
LabyMod/server-media pull request #1161
Opened 2024-06-15 08:25 UTC by Craftportal

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-06-15 12:11 UTC, DoJapHD requested changes

2024-06-15 12:11 UTC, DoJapHD commented on minecraft_servers/craftportal/manifest.json
> +      "teamspeak":"endertime.net",
It's the Endertime TeamSpeak?

2024-06-18 20:41 UTC, Craftportal commented on minecraft_servers/craftportal/manifest.json
> +      "teamspeak":"endertime.net",
Oh I will fix it

2024-06-19 16:53 UTC, DoJapHD approved these changes

2024-06-19 16:53 UTC, merged