voasis
LabyMod/server-media pull request #1165
Opened 2024-06-17 09:43 UTC by aquestry

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-06-17 10:48 UTC, maaaathis requested changes

2024-06-17 10:48 UTC, maaaathis commented on minecraft_servers/voasis/background.png
Compress

2024-06-17 10:48 UTC, maaaathis commented on minecraft_servers/voasis/background@2x.png
Compress

2024-06-17 10:48 UTC, maaaathis commented on minecraft_servers/voasis/manifest.json
> +    "%.voasis.de"
Doesn't look like a real wildcard
![image](https://github.com/LabyMod/server-media/assets/37186532/45fdee67-d8c8-4e28-bf8a-e4b3fdaa2d92)

2024-06-17 10:48 UTC, maaaathis commented on minecraft_servers/voasis/manifest.json
> +    "web_support": "https://voasis.de/index.php?route=/forum",
`web_support` cannot be a forum; provide a faq or contact page or remove

2024-06-17 12:46 UTC, aquestry commented
i think i now have everything needed

2024-06-19 16:55 UTC, DoJapHD approved these changes

2024-06-19 16:55 UTC, merged