Add Ikara
LabyMod/server-media pull request #1187
Opened 2024-06-25 03:55 UTC by oipika

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-06-25 05:43 UTC, maaaathis requested changes

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/background.png
Compress this file

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/background@2x.png
Compress this file

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/manifest.json
> +    "web_support": "https://ikara.gg/discord",
`web_support` cannot be a discord server or forum; use a contact form, faq or similar or remove

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/manifest.json
> +    "%.ikara.gg"
Doesn't look like a real wildcard
<img width="823" alt="image" src="https://github.com/LabyMod/server-media/assets/37186532/70851824-3664-4cc3-aed9-435656a9ac84">

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/manifest.json
> +    "web": "https://ikara.gg",
No real content; if website does not exist, remove it

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/manifest.json
> +      "url": "https://www.Ikara.gg/Discord",
Reserved for a own landing page for your gamemode, not a general url

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/manifest.json
> +      "url": "https://www.Ikara.gg/Discord",
Reserved for a own landing page for your gamemode, not a general url

2024-06-25 05:43 UTC, maaaathis commented on minecraft_servers/ikara/manifest.json
> +      "url": "https://www.Ikara.gg/Discord",
Reserved for a own landing page for your gamemode, not a general url

2024-06-26 08:25 UTC, DoJapHD approved these changes

2024-06-26 08:25 UTC, merged