Add Crystopia.net
LabyMod/server-media pull request #1190
Opened 2024-06-28 18:57 UTC by tnsjesper

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

2024-06-28 19:00 UTC, tnsjesper commented
What is wrong?

2024-06-29 10:16 UTC, DoJapHD commented
Seems to have been a bug, works now

2024-06-29 10:17 UTC, DoJapHD requested changes

2024-06-29 10:17 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +      "web_shop": "https://shop.crystopia.net",
Not reachable

2024-06-29 10:17 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +      "web_support": "https://www.crystopia.net/index.php?route=/wiki",
404

2024-06-29 10:17 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +        "url": "https://www.crystopia.net/index.php?route=/games/smp/",
404

2024-06-29 11:20 UTC, tnsjesper commented
Yes i have fixed.

2024-06-29 11:38 UTC, DoJapHD approved these changes

2024-06-29 11:38 UTC, merged