Added InvasionZ
LabyMod/server-media pull request #1206
Opened 2024-07-14 11:37 UTC by AucuneInspiexe

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-07-17 19:14 UTC, DoJapHD requested changes

2024-07-17 19:14 UTC, DoJapHD commented on minecraft_servers/invasionz/manifest.json
> +    "%.invasionz.net",
Not a wildcard
https://i.imgur.com/mXstph9.png

2024-07-17 19:14 UTC, DoJapHD commented on minecraft_servers/invasionz/manifest.json
> +    "%.lunamc.fr"
Not a wildcard
https://i.imgur.com/oatF9xb.png

2024-07-17 19:15 UTC, DoJapHD commented
Server is in maintenance mode; reopen PR once server is publicly available

2024-07-17 19:15 UTC, closed without merging

2024-07-18 06:39 UTC, AucuneInspiexe commented
Hi, when you replied it was just our MOTD that wasn't updating, but it's our fault. Now it's actually in maintenance and should be up in 6H, for the wildcards, we actually just have play.lunarmc.fr and play.invasionz.net, how should i make it so that we know those two ips instead of wildcards ? Should i just put play.invasionz.net and play.lunamc.net instead of %.invasionz.net ect ?