Add RangeMC.net
LabyMod/server-media pull request #1207
Opened 2024-07-15 15:24 UTC by RootException

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-07-15 19:40 UTC, maaaathis requested changes

2024-07-15 19:40 UTC, maaaathis commented on minecraft_servers/rangemc/background.png
Compress this file

2024-07-15 19:40 UTC, maaaathis commented on minecraft_servers/rangemc/background@2x.png
Compress this file

2024-07-15 19:40 UTC, maaaathis commented on minecraft_servers/rangemc/manifest.json
> +    "web_support": "https://rangemc.net/support",
Cannot be hidden behind a login mask; provide a classic faq or contact form or remove

2024-07-15 19:40 UTC, maaaathis commented on minecraft_servers/rangemc/manifest.json
> +      "name": "JumpWorld",
key doesn't match to name

2024-07-15 19:40 UTC, maaaathis commented on minecraft_servers/rangemc/manifest.json
> +      "url": "https://www.timolia.de/games#dna",
I don't think that's what you want here...

2024-07-16 09:49 UTC, RootException commented
Suggestions Done

2024-07-17 19:15 UTC, DoJapHD approved these changes

2024-07-17 19:16 UTC, merged