Add Diamondsucht.de
LabyMod/server-media pull request #1208
Opened 2024-07-15 18:15 UTC by FirstRockety

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-07-15 19:36 UTC, maaaathis requested changes

2024-07-15 19:36 UTC, maaaathis commented on minecraft_servers/diamondsucht/manifest.json
> +    "%.diamondsucht.de"
Doesnt look like a real wildcard
![image](https://github.com/user-attachments/assets/ef6b3458-8e03-4f2d-bd2f-f77dca2dbb69)

2024-07-15 19:36 UTC, maaaathis commented on minecraft_servers/diamondsucht/manifest.json
> +    "discord": "https://diamondsucht.de/discord"
Reserved for partners only; change to a normal discord.gg/[INVITE] url

2024-07-17 19:16 UTC, DoJapHD approved these changes

2024-07-17 19:16 UTC, merged