Added KeinePixel to server-media
LabyMod/server-media pull request #1210
Opened 2024-07-15 21:10 UTC by whynotmax

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-07-16 04:51 UTC, maaaathis requested changes

2024-07-16 04:51 UTC, maaaathis commented on minecraft_servers/keinepixel/manifest.json
> +    "%.keinepixel.net"
Doesn't look like a real wildcard
<img width="850" alt="image" src="https://github.com/user-attachments/assets/39ef3b82-63db-44d4-84b6-615d28e991da">

2024-07-16 09:03 UTC, whynotmax commented
Removed wildcard section

2024-07-17 19:17 UTC, DoJapHD approved these changes

2024-07-17 19:17 UTC, merged