Update keinepixel
LabyMod/server-media pull request #1215
Opened 2024-07-20 16:02 UTC by whynotmax

## Type of change

- [ ] Add new directory for a server
- [X] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments
- Updated manifest.json

2024-07-20 16:13 UTC, whynotmax commented
not offline blud

2024-07-20 20:20 UTC, DoJapHD requested changes

2024-07-20 20:20 UTC, DoJapHD commented on minecraft_servers/keinepixel/manifest.json
> +     "city": "Walldorf",
Are you sure that your server is located in Walldorf or is it still our default location?

2024-07-20 21:22 UTC, whynotmax commented
Sorry, changed it to "Markdorf" :)

2024-07-21 09:28 UTC, DoJapHD approved these changes

2024-07-21 09:28 UTC, merged