Update CrowtyCraft Network server-media
LabyMod/server-media pull request #1219
Opened 2024-07-22 16:03 UTC by LucasitoInDev

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-07-23 22:21 UTC, DoJapHD requested changes

2024-07-23 22:21 UTC, DoJapHD commented on minecraft_servers/crowtycraft/manifest.json
> +      "name": "SkyBlock 1.20.4"
Probably wrong name?

2024-07-23 23:42 UTC, LucasitoInDev commented on minecraft_servers/crowtycraft/manifest.json
> +      "name": "SkyBlock 1.20.4"
Yes! I will write the good one, sorry ♥

2024-07-24 18:04 UTC, DoJapHD approved these changes

2024-07-24 18:04 UTC, merged