Update manifest
LabyMod/server-media pull request #1230
Opened 2024-07-26 12:02 UTC by Kallecrafter

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-08-02 16:22 UTC, Kallecrafter reviewed
fixed

2024-08-04 12:07 UTC, maaaathis requested changes

2024-08-04 12:07 UTC, maaaathis commented on minecraft_servers/craftergang/manifest.json
> +    "%.craftergang.net"
Doesn't look like a real wildcard:
![image](https://github.com/user-attachments/assets/2532a33a-2809-4f0f-99ca-af249a586620)

2024-08-04 12:07 UTC, maaaathis commented on minecraft_servers/craftergang/manifest.json
> +    "rename_to_minecraft_name": true
Reservered for partners only; change this back to `false` if you're not a LabyMod partner

2024-08-04 12:47 UTC, Kallecrafter commented
![image](https://github.com/user-attachments/assets/002bc85e-ac4a-4ff6-a84d-24fbbb5b8273)

2024-08-04 13:08 UTC, Kallecrafter commented
Yes, but if I don't use %. Then the manifest is considered faulty.

2024-08-04 13:10 UTC, Kallecrafter commented
> > ![image](https://private-user-images.githubusercontent.com/81524111/354902581-002bc85e-ac4a-4ff6-a84d-24fbbb5b8273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NzY5MTksIm5iZiI6MTcyMjc3NjYxOSwicGF0aCI6Ii84MTUyNDExMS8zNTQ5MDI1ODEtMDAyYmM4NWUtYWM0YS00ZmY2LWE4NGQtMjRmYmJiNWI4MjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZDM0NzdhMDk5ZmM3OWUyZDQxYmIwZTczY2ZjMmVhODA0ZTUyZjc3ZWVjOTJiNWU1Mjc5OTRjYTczZjI4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_Eh040FKWYmBRFNNVIWtqU3gOZDYW0b_ATNrYGTrmk)
> 
> Yeah, thats the right place. A wildcard need to start with a `%.`

Here ist the Error:
 Invalid wildcard entry. Each entry must start with **%.**. Further information here: https://en.wikipedia.org/wiki/Wildcard_DNS_record (`server_wildcards`)

2024-08-04 13:14 UTC, Nils-afk commented
Just replace the normal with %.craftergang.net

2024-08-04 13:17 UTC, maaaathis commented
> Just replace craftergang.net with %.craftergang.net

If it's really a wildcard^^ (https://en.wikipedia.org/wiki/Wildcard_DNS_record)

2024-08-04 13:27 UTC, Nils-afk commented
> > Just replace craftergang.net with %.craftergang.net
> 
> If it's really a wildcard^^ (https://en.wikipedia.org/wiki/Wildcard_DNS_record)

He only has to add an "A-Record" The name * and the server IP and that's it

2024-08-04 14:46 UTC, Kallecrafter commented
> > > Just replace craftergang.net with %.craftergang.net
> > 
> > 
> > If it's really a wildcard^^ (https://en.wikipedia.org/wiki/Wildcard_DNS_record)
> 
> He only has to add an "A-Record" The name * and the server IP and that's it

And that would look like this?

2024-08-04 21:32 UTC, Nils-afk commented
Yes

2024-08-09 12:51 UTC, Kallecrafter commented
fixed

2024-08-09 12:59 UTC, maaaathis requested changes

2024-08-09 12:59 UTC, maaaathis commented on minecraft_servers/craftergang/manifest.json
> +    "%.craftergang.net",
Not a real wildcard
<img width="835" alt="Google Chrome 2024-08-09 14 58 36" src="https://github.com/user-attachments/assets/a5058b64-e832-464e-a6d3-d023ae34a6c9">

2024-08-09 12:59 UTC, maaaathis commented on minecraft_servers/craftergang/manifest.json
> +    "%.craftergang.de"
Not a real wildcard
<img width="837" alt="Shottr 2024-08-09 14 58 43" src="https://github.com/user-attachments/assets/e08c1062-2944-46eb-bd52-0b7e9482e551">

2024-08-09 13:35 UTC, Kallecrafter commented
Server is not Offline!!!
![image](https://github.com/user-attachments/assets/61e9596a-7441-4064-8005-d0c7775e0c96)

2024-08-09 13:36 UTC, Kallecrafter commented
![image](https://github.com/user-attachments/assets/3b610061-0ef2-46f9-8ac7-bd952619dc2b)
![image](https://github.com/user-attachments/assets/6adbdafa-eac8-40bf-86fe-112be2624d72)

2024-08-09 13:39 UTC, Kallecrafter commented
Old Merges from the Server:
![image](https://github.com/user-attachments/assets/57cfdd2e-20a4-4461-ab96-05c88dcf2faa)
![image](https://github.com/user-attachments/assets/928526b1-b2f0-4c49-ad82-0fed986f0db8)

craftergang.net was set in "server_wildcards" and worked flawlessly.

2024-08-09 13:42 UTC, Kallecrafter commented
![image](https://github.com/user-attachments/assets/8184f6e3-3db4-491b-8271-a06c1e26c185)

2024-08-09 14:21 UTC, maaaathis commented
> **I have both the ip craftergang.de and craftergang.net If I set the wildcard without a "%" sign in front of the IP, the system tells me there are problems. If I put one in front of it, you tell me a problem. I don't know what to do. For example, I have craftergang.de as Domain and craftergang.net as subdomain which also works.**

See the definition for a wildcard dns entry: https://en.wikipedia.org/wiki/Wildcard_DNS_record

2024-08-09 15:04 UTC, Kallecrafter commented
**Please just merge it. It works perfectly. DoJapHD had always merged it before, with the same domain. I don't know what the problem is.**

2024-08-16 10:10 UTC, DoJapHD approved these changes

2024-08-16 10:11 UTC, merged