manifest.json
LabyMod/server-media pull request #1236
Opened 2024-08-01 15:32 UTC by Im7S1

add discord id
user stats

## Type of change

- [ ] Add new directory for a server
- [ stats player - discord id ] Update directory of a server
- [ teamspeak ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-08-04 12:08 UTC, maaaathis requested changes
And please fix your indentations

2024-08-04 12:08 UTC, maaaathis commented on minecraft_servers/blocksmc/manifest.json
>      "discord": "https://discord.gg/BlocksMC",
```suggestion
    "discord": "https://discord.gg/BlocksMC"
```

2024-08-04 12:08 UTC, maaaathis commented on minecraft_servers/blocksmc/manifest.json
>    }
```suggestion
  },
```

2024-08-04 12:09 UTC, maaaathis commented
Duplicate of #1237

2024-08-05 15:43 UTC, DoJapHD commented
Duplicate

2024-08-05 15:43 UTC, closed without merging