Add VaroVision.EU
LabyMod/server-media pull request #1259
Opened 2024-08-09 21:43 UTC by Kalibrier

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-08-10 08:20 UTC, DoJapHD requested changes

2024-08-10 08:20 UTC, DoJapHD commented on minecraft_servers/varovision.eu/manifest.json
> +  "server_name": "VaroVision.EU",
Just use lowercase `varovision` and change the folder name to that, too

2024-08-10 08:21 UTC, DoJapHD commented
Server is not reachable

2024-08-11 20:16 UTC, Kalibrier commented
Please add the server

2024-08-12 08:30 UTC, DoJapHD requested changes
Server has to be publicly available

2024-08-12 08:30 UTC, DoJapHD commented on minecraft_servers/varovision.eu/manifest.json
> +  "server_name": "varovision.eu",
As already mentioned before, only use "varovision"!

2024-08-12 11:52 UTC, Kalibrier commented
I think I did it correctly now

2024-08-12 13:47 UTC, DoJapHD approved these changes

2024-08-12 13:47 UTC, merged