Add Porgverse
LabyMod/server-media pull request #126
Opened 2021-08-29 12:35 UTC by Jazzkuh

## Type of change

- [x] Add new directory for a server
- [x] Update directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2021-08-29 18:08 UTC, JakobBruening requested changes
Please compress your images.

2021-08-29 18:36 UTC, Jazzkuh commented
> Please compress your images.

I did compress them

2021-08-29 19:17 UTC, JakobBruening commented
Really? I can still improve the file size: https://compresspng.com/

2021-08-29 19:37 UTC, Jazzkuh commented
> Really? I can still improve the file size: https://compresspng.com/

Oh ill take a look at it tomorrow then!

2021-08-30 15:32 UTC, Jazzkuh commented
> > Really? I can still improve the file size: https://compresspng.com/
> 
> Oh ill take a look at it tomorrow then!

Done

2021-08-31 00:11 UTC, JakobBruening requested changes
- background-min.png
- background@2x-min.png
- icon-min.png
- icon@2x-min.png

The file names are not supported. [Documentation reference](https://github.com/LabyMod/server-media/blob/master/docs/Files.md)

BR, Jakob

2021-08-31 00:11 UTC, JakobBruening commented on minecraft_servers/porgverse/manifest.json
> +    "country_code": "nl"
Please use uppercase here.

2021-08-31 06:59 UTC, Jazzkuh commented on minecraft_servers/porgverse/manifest.json
> +    "country_code": "nl"
Done

2021-08-31 11:23 UTC, JakobBruening approved these changes
Looks good now, thank you!

2021-08-31 11:24 UTC, merged