update background@2x image
LabyMod/server-media pull request #1277
Opened 2024-08-20 18:07 UTC by Kallecrafter

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [x] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-08-20 18:47 UTC, Nils-afk commented
The new Image has the wrong size. Yours is W: 1920px | H: 1020px. It should be W: 1920px | H: 1080px Than Convert it and it should work!

2024-08-20 19:11 UTC, Kallecrafter commented
craftergang.de it's not Offline!
![image](https://github.com/user-attachments/assets/d08c6580-9eea-42ee-aa62-e2df3e8f995c)

2024-08-21 18:21 UTC, maaaathis commented
> Its Online! ![image](https://private-user-images.githubusercontent.com/81524111/359973661-98e0fbc1-e2bd-4225-96d1-6bb9959d3750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjQ2OTgsIm5iZiI6MTcyNDI2NDM5OCwicGF0aCI6Ii84MTUyNDExMS8zNTk5NzM2NjEtOThlMGZiYzEtZTJiZC00MjI1LTk2ZDEtNmJiOTk1OWQzNzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE4MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhN2RjOTllMWVkODk2ZTgzODJjNjQyYTJhNWM2N2FlMzgxZGVlMzIzYWE2NTA5MzZjYWRjOGE0NDEzNmE3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iccB_TPBWuFXXq7381sTOXbgzSrzUzfA3n5MPABXKrg) Please Fix the Bot Problem!

This is an external provider calling your server. For this reason, the action says “[...] could be offline” and not “is offline”. However, this is absolutely no problem if your server is really online.

2024-08-25 12:25 UTC, DoJapHD requested changes

2024-08-25 12:25 UTC, DoJapHD commented on minecraft_servers/craftergang/background@2x.png
Compress image

2024-08-25 14:59 UTC, Kallecrafter commented
Image was compressed

2024-08-25 15:25 UTC, Kallecrafter commented
Now everything is correct. Now you can merge (:

2024-08-25 20:29 UTC, DoJapHD approved these changes

2024-08-25 20:29 UTC, merged

2024-10-29 14:13 UTC, Kallecrafter commented
closed