Added CraftedHorizon
LabyMod/server-media pull request #1288
Opened 2024-08-22 11:53 UTC by FabiChan99

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-08-22 14:09 UTC, maaaathis requested changes

2024-08-22 14:09 UTC, maaaathis commented on minecraft_servers/craftedhorizon/background@2x.png
Compress this file

2024-08-22 14:53 UTC, FabiChan99 commented on minecraft_servers/craftedhorizon/background@2x.png
done

2024-08-25 12:31 UTC, DoJapHD approved these changes

2024-08-25 12:31 UTC, merged