Add CityMine
LabyMod/server-media pull request #1339
Opened 2024-09-12 18:59 UTC by octolexgaming

## Type of change

- [x ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x ] I have created the manifest.json with the required values

## Further comments

2024-09-12 19:27 UTC, DoJapHD requested changes
Move all files into own folder called `citymine` inside of the `minecraft_servers` folder

2024-09-12 19:27 UTC, DoJapHD commented on minecraft_servers/manifest.json
> +    "grundstücke": {
JSON Convention error; change to `grundstuecke`

2024-09-13 05:35 UTC, DoJapHD commented
That's still not inside of a folder...

2024-09-13 11:38 UTC, octolexgaming commented
I'm new to github how do I do that?

2024-09-13 11:57 UTC, closed without merging