Update manifest.json
LabyMod/server-media pull request #134
Opened 2021-09-05 11:06 UTC by dergrosehd

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2021-09-05 11:10 UTC, JakobBruening requested changes

2021-09-05 11:10 UTC, JakobBruening commented on minecraft_servers/pvparmy/manifest.json
> +    "web": "https://pvparmy.net",
New website is also in maintenance. Please remove the line to prevent a redirect to a maintenance-website.

2021-09-05 11:10 UTC, JakobBruening commented
And your server is also in maintenance. When will the server be available again?

2021-09-07 19:23 UTC, dergrosehd commented
The website is now published and our network is also back from maintenance. The API also gave me something wrong. As information, our network is not yet finally open but in a closed beta, which can only be viewed with a beta key. For the review I can gladly provide two beta keys.

`fje357hh`
`oq7txr6x`

The beta keys can be redeemed after joining the network with /beta KEY.

2021-09-08 14:11 UTC, JakobBruening approved these changes
Okay, thank you!

2021-09-08 14:11 UTC, merged