Added GalaxyMine.de
LabyMod/server-media pull request #1353
Opened 2024-09-21 21:58 UTC by TrismoTV

## Type of change

- [ x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x ] I have created the manifest.json with the required values

## Further comments

2024-09-21 22:05 UTC, TrismoTV reviewed
...

2024-09-22 08:21 UTC, DoJapHD requested changes

2024-09-22 08:21 UTC, DoJapHD commented on minecraft_servers/galaxymine/manifest.json
> +    "web": "https://galaxymine.de",
Just a default Apache2 page

2024-09-22 08:21 UTC, DoJapHD commented on minecraft_servers/galaxymine/manifest.json
> +    "web_shop": "https://shop.galaxymine.de",
Not reachable

2024-09-22 10:00 UTC, DoJapHD commented
Server is in maintenance mode;
Reopen PR once server is publicly available

2024-09-22 10:00 UTC, closed without merging

2024-09-22 11:01 UTC, TrismoTV commented
Please reopen the PR.

2024-09-22 11:33 UTC, TrismoTV reviewed
.