New Images and Mainfest.json
LabyMod/server-media pull request #1357
Opened 2024-09-22 17:59 UTC by EinfachFloTV

## Type of change

Images and Mainfest.json

2024-09-22 19:20 UTC, DoJapHD requested changes

2024-09-22 19:20 UTC, DoJapHD commented on minecraft_servers/craftportal/manifest.json
> +      "web": "https://craftportal.net",
Not reachable

2024-09-23 06:44 UTC, DoJapHD requested changes

2024-09-23 06:44 UTC, DoJapHD commented on minecraft_servers/craftportal/manifest.json
> +      "web": "https://www.craftportal.net",
https://i.imgur.com/hjhON0F.png

2024-09-23 13:01 UTC, mrcraftreal commented on minecraft_servers/craftportal/manifest.json
> +      "web": "https://www.craftportal.net",
https://postimg.cc/3d5vY56r

2024-09-24 05:44 UTC, DoJapHD requested changes

2024-09-24 05:44 UTC, DoJapHD commented on minecraft_servers/craftportal/manifest.json
> +      "web": "https://www.craftportal.net",
https://i.imgur.com/b5b6Niw.png

2024-09-27 20:39 UTC, mrcraftreal commented
Our website should now be working again and I have removed Teamspeak.

2024-09-27 22:05 UTC, DoJapHD requested changes

2024-09-27 22:05 UTC, DoJapHD commented on minecraft_servers/craftportal/manifest.json
> +      "web": "https://www.craftportal.net",
If website is in maintenance mode, there's no real meaning behind having it in here
If the website will be in maintenance for longer, remove

2024-09-28 13:27 UTC, mrcraftreal commented
Okay. Can you please delete Teamspeak?

2024-10-04 10:03 UTC, DoJapHD commented
The PR owner can do that, I won't.

2024-10-08 18:22 UTC, DoJapHD commented
Inactive PR

2024-10-08 18:22 UTC, closed without merging