Update
LabyMod/server-media pull request #1385
Opened 2024-10-11 07:59 UTC by Ralfpro

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-10-11 08:51 UTC, Ralfpro commented
My Server

2024-10-16 05:27 UTC, maaaathis requested changes

2024-10-16 05:27 UTC, maaaathis commented on minecraft_servers/networknougat/manifests.json
File has to be named `manifest.json`

2024-10-18 14:18 UTC, DoJapHD commented
Inactive PR

2024-10-18 14:18 UTC, closed without merging