Update RubyMC.net server mappings
LabyMod/server-media pull request #1391
Opened 2024-10-15 11:30 UTC by Plunzi

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-10-15 17:05 UTC, DoJapHD requested changes

2024-10-15 17:05 UTC, DoJapHD commented on minecraft_servers/rubymc/manifest.json
> +      "web_shop":"https://shop.rubymc.net",
Not reachable

2024-10-15 17:05 UTC, DoJapHD commented on minecraft_servers/rubymc/manifest.json
> +      "youtube":"https://www.youtube.com/@rubymcnet"
Not found

2024-10-16 12:58 UTC, Plunzi commented
@DoJapHD The Web-Shop is currently undergoing some changes therefore it is not reachable, therefore the values entered are correct. Thanks for the review anyways.

2024-10-16 18:09 UTC, DoJapHD commented
How long will that take?

2024-10-18 08:28 UTC, Plunzi commented
Unsure, I'd guess it will take some more weeks.

2024-10-18 09:30 UTC, DoJapHD commented
Then remove from PR, you can add again it if it's done

2024-10-25 14:36 UTC, DoJapHD commented
Inactive PR

2024-10-25 14:36 UTC, closed without merging