add froschmc
LabyMod/server-media pull request #1443
Opened 2024-11-10 18:28 UTC by FakeBlack1

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-11-10 18:29 UTC, DoJapHD requested changes
Still the same changes as requested in the last PR

2024-11-10 18:32 UTC, FakeBlack1 commented
hat es funktioniert?

2024-11-10 18:33 UTC, DoJapHD requested changes

2024-11-10 18:33 UTC, DoJapHD commented on minecraft_servers/froschmc/manifest.json
> +    "%.froschmc.de"
Not a real wildcard

2024-11-10 18:33 UTC, DoJapHD commented on minecraft_servers/froschmc/manifest.json
> +    "web": "https://www.froschmc.de",
Not reachable

2024-11-10 18:33 UTC, DoJapHD commented on minecraft_servers/froschmc/manifest.json
> +    "web_shop": "https://froschmc.de",
Not reachable

2024-11-10 18:33 UTC, DoJapHD commented on minecraft_servers/froschmc/manifest.json
> +    "teamspeak": ""
Remove

2024-11-10 18:33 UTC, DoJapHD commented on minecraft_servers/froschmc/manifest.json
> +  "yt_trailer": ""
Remove

2024-11-10 18:33 UTC, DoJapHD commented on minecraft_servers/froschmc/manifest.json
> +      "^(|§8»\\n)(§[a-f0-9]§?l?(?<rank>\\S+))§r §8\\| §7(?<sender>[a-zA-Z0-9_]{2,16})§r §8» §7(?<message>.*)(|\\n§8»)$"
Are you sure that's your regex?

2024-11-12 05:45 UTC, DoJapHD requested changes

2024-11-12 05:45 UTC, DoJapHD commented on minecraft_servers/froschmc/background.png
Compress image

2024-11-12 05:45 UTC, DoJapHD commented on minecraft_servers/froschmc/background@2x.png
Compress image

2024-11-16 10:15 UTC, closed without merging