Update Server
LabyMod/server-media pull request #1446
Opened 2024-11-13 16:35 UTC by mrcraftreal

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-11-13 16:59 UTC, maaaathis requested changes

2024-11-13 16:59 UTC, maaaathis commented on minecraft_servers/craftportal/manifest.json
> +      "brand": {
Place `brand` outside of the `gamemodes` object

2024-11-16 15:21 UTC, DoJapHD requested changes

2024-11-18 20:43 UTC, DoJapHD commented
Please try opening another PR

2024-11-18 20:43 UTC, closed without merging