Minevale cb melone edit
LabyMod/server-media pull request #1449
Opened 2024-11-14 11:39 UTC by Plattio

## Type of change

- [ ] Add new directory for a server
- [x ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x ] I have created the manifest.json with the required values

## Further comments

2024-11-14 11:44 UTC, maaaathis requested changes

2024-11-14 11:44 UTC, maaaathis commented on minecraft_servers/minevale/manifest.json
> +    "%.minevale.de",
Doesn't look like a real wildcard:
<img width="882" alt="image" src="https://github.com/user-attachments/assets/9a220cbe-74ac-4f60-a240-2919be2b0966">

2024-11-14 11:44 UTC, maaaathis commented on minecraft_servers/minevale/manifest.json
> +    "%.minevale.eu"
Doesn't look like a real wildcard:
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/08c8ab4c-6fbb-4df4-987f-d29f40fd6d86">

2024-11-14 11:44 UTC, maaaathis commented on minecraft_servers/minevale/manifest.json
> +      "name": "CityBuild Melone",
key doesn't match to name

2024-11-21 15:29 UTC, DoJapHD commented
Inactive PR

2024-11-21 15:29 UTC, closed without merging