added stein games server from ErzeStein
LabyMod/server-media pull request #1451
Opened 2024-11-14 17:05 UTC by danzelgeb

## Type of change

- [x ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x ] I have created the manifest.json with the required values

## Further comments

2024-11-14 17:51 UTC, maaaathis requested changes

2024-11-14 17:51 UTC, maaaathis commented on minecraft_servers/steinegames/manifest.json
> +      "web": "https://steine-games.de",
not reachable

2024-11-15 06:19 UTC, danzelgeb commented on minecraft_servers/steinegames/manifest.json
> +      "web": "https://steine-games.de",
Removed not reacheble website

2024-11-15 08:03 UTC, DoJapHD approved these changes

2024-11-15 08:03 UTC, DoJapHD commented
Ah wait, the server is in maintenance mode
Open another PR once server is publicly available

2024-11-15 08:03 UTC, closed without merging