Update Melvin501.de
LabyMod/server-media pull request #1460
Opened 2024-11-20 15:49 UTC by MELONEODERSO

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-11-20 17:04 UTC, maaaathis requested changes

2024-11-20 17:04 UTC, maaaathis commented on minecraft_servers/melvin501/background.png
Compress this file

2024-11-20 17:04 UTC, maaaathis commented on minecraft_servers/melvin501/background@2x.png
Compress this file

2024-11-21 09:03 UTC, DoJapHD approved these changes

2024-11-21 09:03 UTC, merged