manifest.json Erstellt
LabyMod/server-media pull request #1468
Opened 2024-11-23 11:54 UTC by NextPlatziReal

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

2024-11-23 12:00 UTC, NextPlatziReal commented
.

2024-11-23 12:04 UTC, maaaathis requested changes
- directory name has to be lowercase

- icon.png is not given, but it is required.

- icon@2x.png is not given, but it is required.

2024-11-23 14:21 UTC, DoJapHD reviewed
Change folder name to lowercase

2024-11-23 14:21 UTC, DoJapHD commented on minecraft_servers/PlatziLegends/background.png
Compress image

2024-11-23 14:21 UTC, DoJapHD commented on minecraft_servers/PlatziLegends/background@2x.png
Compress image

2024-11-23 15:25 UTC, DoJapHD commented
Our check is faulty, ignore the error

2024-11-23 15:34 UTC, DoJapHD commented
Again, our script is broken right now.
Please wait.

2024-12-02 07:48 UTC, DoJapHD commented
Inactive PR

2024-12-02 07:48 UTC, closed without merging