Add alchemynetwork
LabyMod/server-media pull request #1490
Opened 2024-11-27 23:01 UTC by swagviper

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-11-28 19:55 UTC, maaaathis requested changes

2024-11-28 19:55 UTC, maaaathis commented on minecraft_servers/alchemynetwork/manifest.json
> +        "web_shop": "https://www.alchemynetwork.net"
Doesn't look like a web shop

2024-11-28 19:55 UTC, maaaathis commented on minecraft_servers/alchemynetwork/manifest.json
> +            "name": "Blizzard",
key doesn't match to name

2024-11-30 14:58 UTC, DoJapHD approved these changes

2024-11-30 14:58 UTC, merged