✨Added gamemodes, location, supported languages and removed some useless bits. ✨
LabyMod/server-media pull request #195
Opened 2021-12-27 18:17 UTC by SlenkyDev

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2021-12-28 14:22 UTC, scrummer requested changes
Please in general:
- Have a look at the formatting (it does not matter if the indentation is 2 or 4 spaces, but keep it consistent)

2021-12-28 14:22 UTC, scrummer commented on minecraft_servers/lendmark/manifest.json
> +      "discord": "https://discord.lendmark.sk",
Please change this back to an official Discord invite link (referring to [docs/Manifest.md#discord-url](https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md#discord-url)

2021-12-28 14:22 UTC, scrummer commented on minecraft_servers/lendmark/manifest.json
> +    "rename_to_minecraft_name": true
Please change this value to `false` (currently no support for non-partner servers)

2021-12-28 14:33 UTC, scrummer requested changes
Indentation looks good now but you removed all the whitespaces between keys and values. You can keep those :)

2021-12-28 14:34 UTC, SlenkyDev commented
> Indentation looks good now but you removed all the whitespaces between keys and values. You can keep those :)

I used a JSON formatter for that because I suck at formatting. Also removed the gamemodes as we change them quite often and currently we don't have many.

2021-12-28 14:38 UTC, scrummer commented
@SlenkyDev Then I would recommend you this one, looks like it does everything right (check that you've selected 4 or 2 space indentation!)

2021-12-28 14:41 UTC, SlenkyDev commented
Thanks!

2021-12-29 09:49 UTC, scrummer commented
Looks good now, thank you very much!

2021-12-29 09:49 UTC, merged