Add GoliCraft
LabyMod/server-media pull request #196
Opened 2021-12-28 06:09 UTC by Solyze

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2021-12-28 14:31 UTC, scrummer requested changes
It seems like you uploaded all the files twice (once to `/golicraft/` and once to `/minecraft_servers/golicraft/`). Please fix this, the server directory must be placed into the `/minecraft_servers` directory

2021-12-28 14:31 UTC, scrummer commented on minecraft_servers/golicraft/manifest.json
> +    "youtube": "https://www.youtube.com/GoliCraft/"
Please remove the trailing slash here

2021-12-28 16:02 UTC, Solyze commented
Sorry about the double upload, didn't notice that whilst I did that at like 6AM
I think everything should be good now

2021-12-29 09:55 UTC, scrummer commented
Thank you!

2021-12-29 09:55 UTC, merged