apfelnetzwerk
LabyMod/server-media pull request #200
Opened 2021-12-28 15:11 UTC by Apfelnetzwerk

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2021-12-28 15:25 UTC, PartikelTTV commented
seem's legit

2021-12-29 10:09 UTC, JakobBruening requested changes

2021-12-29 10:09 UTC, JakobBruening commented on minecraft_servers/apfelnetzwerk/manifest.json
> +    "server_id": "851012884674641973"
Remove quotes, as it is the case in our example. Currently, it is a string containing your server id.
https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md#example-manifestjson-file

2021-12-29 10:14 UTC, scrummer requested changes

2021-12-29 10:14 UTC, scrummer commented on minecraft_servers/apfelnetzwerk/manifest.json
> +    "BedWars": {
change all the keys to lower-case (the name can stay like this) - for every gamemode

2021-12-29 10:14 UTC, scrummer commented on minecraft_servers/apfelnetzwerk/manifest.json
> +    "web_support": "https://support.apfelnetzwerk.de/",
Remove the trailing slashes for all social domains

2021-12-29 21:48 UTC, scrummer commented
Looks good, thank you!

2021-12-29 21:48 UTC, merged