Removed server distaria, add server tariamc (Distaria was renamed TariaMC)
LabyMod/server-media pull request #264
Opened 2022-06-04 12:10 UTC by EinsLucaaa

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

Distaria was renamed TariaMC

2022-06-04 23:40 UTC, JakobBruening requested changes

2022-06-04 23:40 UTC, JakobBruening commented on minecraft_servers/tariamc/manifest.json
> +        "rename_to_minecraft_name": true
Please use `false`, as this is the default value. We will accept `true` as a value here only for verified partners.

2022-06-04 23:40 UTC, JakobBruening commented on minecraft_servers/tariamc/manifest.json
> +        "web": "https://tariamc.net/",
Remove "/" at the end.

2022-06-05 07:00 UTC, EinsLucaaa commented
Done

2022-06-05 10:53 UTC, JakobBruening approved these changes
Thank you! 💪🏽

2022-06-05 10:53 UTC, merged