Add files via upload
LabyMod/server-media pull request #279
Opened 2022-06-21 17:29 UTC by SULDomiYT

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2022-06-22 14:48 UTC, JakobBruening commented on minecraft_servers/sulentia/manifest.json
> +  }
Add comma for valid syntax.

2022-06-22 16:22 UTC, SULDomiYT commented on minecraft_servers/sulentia/manifest.json
> +    "rename_to_minecraft_name": true
the

2022-06-23 17:24 UTC, JakobBruening requested changes
Please compress the images.

2022-06-25 17:58 UTC, JakobBruening approved these changes
Thank you! :)

2022-06-25 17:58 UTC, merged