add mineleague
LabyMod/server-media pull request #300
Opened 2022-07-18 06:50 UTC by soeinyoshi

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2022-07-18 06:54 UTC, soeinyoshi commented
add mineleague

2022-07-18 14:38 UTC, JakobBruening requested changes
Please compress all files, especially the background@2x.png is too large.

2022-07-18 14:38 UTC, JakobBruening commented on minecraft_servers/mineleague/manifest.json
> +      "discord":"https://link.mineleague.eu/discord"
As custom discord invite links are only supported for LabyMod partners at the moment.
Please use a discord invite link.

Documentation reference: https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md#discord-url

2022-07-19 06:21 UTC, soeinyoshi commented
fixed

2022-08-02 19:21 UTC, JakobBruening requested changes
Invalid workflow.json - Fix json!

2022-08-11 19:40 UTC, JakobBruening commented
I will close the PR due to inactivity.
Please re-open or re-create as soon as the changes are applied to your fork.

2022-08-11 19:40 UTC, closed without merging