add Spiritsmc
LabyMod/server-media pull request #316
Opened 2022-08-28 08:35 UTC by not16hir0

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2022-09-01 09:00 UTC, scrummer commented
@not16hir0 Can you (at least) compress your background images? They're reeeally big

2022-09-05 08:05 UTC, niklaswa commented
Hey there, I think, it would be better if you'd remove the logo from the background image as it will get overlayed at the certain places automatically (for example on laby.net)

2022-09-20 12:50 UTC, JakobBruening requested changes

2022-09-20 12:50 UTC, JakobBruening commented on minecraft_servers/Spiritsmc/manifest.json
> +      "discord":"https://discord.gg/spr"
<img width="578" alt="Bildschirmfoto 2022-09-20 um 14 50 03" src="https://user-images.githubusercontent.com/45363287/191262149-90dc87cb-fd6e-476f-9b31-fa3f79a0ab6a.png">

2022-10-07 07:07 UTC, scrummer commented
@not16hir0 Please fix the open issues within the next days. Otherwise we close the PR to keep it all clean.

2022-10-09 16:09 UTC, JakobBruening commented
I will close the PR due to inactivity.
Please re-open or re-create as soon as the comments are resolved.

2022-10-09 16:09 UTC, closed without merging