Add WildWestMC
LabyMod/server-media pull request #321
Opened 2022-09-02 15:13 UTC by Jazzkuh

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2022-09-02 15:26 UTC, Jazzkuh commented
Images failed because of: ```Error: Invalid file name banner.png: https://github.com/LabyMod/server-media/blob/master/docs/Files.md#filestructure: minecraft_servers/timolia/banner.png```

2022-09-10 20:14 UTC, JakobBruening requested changes

2022-09-10 20:14 UTC, JakobBruening commented on minecraft_servers/wildwestmc/manifest.json
> +    "web": "https://wildwestmc.net"
Website is not available.

2022-09-20 12:49 UTC, JakobBruening approved these changes
Thank you! :)

2022-09-20 12:49 UTC, merged