added pommesmc
LabyMod/server-media pull request #328
Opened 2022-09-23 15:25 UTC by Toasty8i

PommesMC.

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2022-09-23 16:09 UTC, Toasty8i commented
Is this good?

2022-10-09 15:43 UTC, JakobBruening requested changes
Please also compress your images.

BR, Jakob

2022-10-09 15:43 UTC, JakobBruening commented on minecraft_servers/pommesmc/manifest.json
> +    "rename_to_minecraft_name": true
Please use `false`, as this is the default value. We will accept `true` as a value here only for verified partners.

2022-10-19 16:59 UTC, JakobBruening commented
Please fix the issue as soon as possible. Otherwise, we would close the PR.

2022-10-22 13:06 UTC, closed without merging