Add BuildMania Network
LabyMod/server-media pull request #36
Opened 2021-07-05 19:03 UTC by Fjuro

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments
Sorry for another PR today :sweat_smile:

2021-07-05 21:46 UTC, JakobBruening requested changes

2021-07-05 21:46 UTC, JakobBruening commented on minecraft_servers/buildmania/manifest.json
> +      "instagram": "http://instagram.buildmania.cz",
Please make this http**s**://

2021-07-06 04:54 UTC, Fjuro commented on minecraft_servers/buildmania/manifest.json
> +      "instagram": "http://instagram.buildmania.cz",
Done, sorry

2021-07-06 06:50 UTC, JakobBruening approved these changes
Thank you! ✌🏽

2021-07-06 06:50 UTC, merged