Added Byens Server Media
LabyMod/server-media pull request #430
Opened 2023-02-18 12:43 UTC by Simonmaribo

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2023-02-18 12:46 UTC, Simonmaribo commented
![image](https://user-images.githubusercontent.com/64478800/219866568-4367fe45-8dcf-40bf-951d-c36ae97e53fd.png)

I hope the player count is high enough for it to be added.

2023-02-27 21:59 UTC, JakobBruening requested changes

2023-02-27 21:59 UTC, JakobBruening commented on minecraft_servers/byen/manifest.json
> +      "web_support": "https://discord.byen.net",
Discord is not supported. Only faq/web support pages are accepted for "web_support".

2023-02-27 21:59 UTC, JakobBruening commented on minecraft_servers/byen/manifest.json
> +      "discord": "https://discord.byen.net"
As custom discord invite links are only supported for LabyMod partners at the moment.
Please use a discord invite link.

Documentation reference: https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md#discord-url

2023-03-14 17:09 UTC, JakobBruening commented
Closed until issues are resolved.

2023-03-14 17:09 UTC, closed without merging

2023-03-14 17:19 UTC, Simonmaribo commented
Alright - a new PR has been created.

2023-03-14 17:19 UTC, Simonmaribo commented
https://github.com/LabyMod/server-media/pull/446