minetropical
LabyMod/server-media pull request #458
Opened 2023-03-20 16:42 UTC by ByToxiii

2023-03-20 21:57 UTC, JakobBruening requested changes
& compress your images

2023-03-20 21:57 UTC, JakobBruening commented on manifest.json
> +	"%.minetropical.eu",
formatting

2023-03-29 21:24 UTC, JakobBruening approved these changes

2023-03-29 21:25 UTC, merged

2023-03-30 21:33 UTC, l3nnartt commented
somehow the subfolder is missing here