Add LosTaroleros Server
LabyMod/server-media pull request #527
Opened 2023-05-29 18:58 UTC by SMarc1

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2023-06-10 09:05 UTC, JakobBruening requested changes
Please compress images!

2023-06-10 09:05 UTC, JakobBruening commented on minecraft_servers/LosTaroleros/manifest.json
> +    "server_name": "LosTaroleros",
must be lowercase

2023-06-15 20:39 UTC, SMarc1 commented
@JakobBruening done

2023-06-16 08:24 UTC, JakobBruening approved these changes

2023-06-16 08:24 UTC, merged