Update Matherion.eu
LabyMod/server-media pull request #55
Opened 2021-07-15 16:57 UTC by Fjuro

About the web-support URL: the owner told me to add a Discord invite there

## Type of change

- [x] Update directory of a server

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2021-07-15 22:10 UTC, JakobBruening requested changes

2021-07-15 22:10 UTC, JakobBruening commented on minecraft_servers/matherion/manifest.json
> +    "web-support": "https://discord.com/invite/mXTBfuS",
That is not the meaning behind it. [A URL to a website is to be specified here](https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md). If there is no website for support, then please remove the line.
It is not a required key.

2021-07-15 22:10 UTC, JakobBruening commented on minecraft_servers/matherion/manifest.json
> +    "web-support": "https://discord.com/invite/mXTBfuS",
That is not the meaning behind it. [A URL to a website is to be specified here](https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md). If there is no website for support, then please remove the line.
It is not a required key.

2021-07-15 22:13 UTC, JakobBruening requested changes

2021-07-15 22:13 UTC, JakobBruening commented on minecraft_servers/matherion/manifest.json
> +    "web-shop": "https://matherion.craftingstore.net",
Please use the correct key here: `web-shop` => `web_shop`
=> [Documentation reference](https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md#available-keys)

2021-07-16 11:12 UTC, Fjuro commented
Fixed, sorry

2021-07-16 12:41 UTC, JakobBruening approved these changes
Great! Thank you very much! ✌

2021-07-16 12:41 UTC, merged