Adding Lalura Network
LabyMod/server-media pull request #621
Opened 2023-07-15 01:44 UTC by ezTxmMC

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2023-07-15 01:49 UTC, Terallixo approved these changes

2023-07-24 06:16 UTC, JakobBruening requested changes

2023-07-24 06:16 UTC, JakobBruening commented on minecraft_servers/lalura/manifest.json
> +      "web": "https://lalura.net",
We only accept working websites. Please fix or remove (you can still add the page later).
![Bildschirmfoto 2023-07-24 um 08 15 26](https://github.com/LabyMod/server-media/assets/45363287/98e70c58-491d-49e2-80d4-99d1bc2a82bc)

2023-07-25 16:46 UTC, JakobBruening approved these changes

2023-07-25 16:47 UTC, merged