Add LegendNation.GG
LabyMod/server-media pull request #656
Opened 2023-08-10 16:10 UTC by ld338

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x]  I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x]  I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x]  I have created the manifest.json with the required values

## Further comments

2023-08-10 16:19 UTC, ld338 commented
Its online, there was just a wrong record.
https://mcapi.us/server/status?ip=legendnation.gg

2023-08-22 15:30 UTC, JakobBruening requested changes
Please also fix json formatting. Use spaces as in our example manifest.json fiel.

2023-08-22 15:30 UTC, JakobBruening commented on minecraft_servers/legendnation/manifest.json
> +		"web_support": "https://legendnation.gg/support",
Page not available. Fix or remove.

2023-08-22 15:30 UTC, JakobBruening requested changes
Please also fix json formatting. Use spaces as in our example manifest.json file.

2023-08-24 18:57 UTC, ld338 commented
Like this?

2023-09-07 09:40 UTC, ld338 commented
@JakobBruening

2023-09-09 09:42 UTC, merged