Added StarDix and GladMC
LabyMod/server-media pull request #658
Opened 2023-08-11 14:42 UTC by JobsonMarinho

Added StarDix
Added GladMC

2023-08-22 15:41 UTC, JakobBruening requested changes

2023-08-22 15:41 UTC, JakobBruening commented on minecraft_servers/gladmc/manifest.json
> +    "web_shop": "https://loja.gladmc.com",
404

2023-08-22 15:41 UTC, JakobBruening commented on minecraft_servers/gladmc/manifest.json
> +    "rename_to_minecraft_name": true
Only supported for partner servers atm.

2023-08-22 15:41 UTC, JakobBruening commented on minecraft_servers/stardix/manifest.json
> +    "rename_to_minecraft_name": true
Only supported for partner servers atm.

2023-08-26 19:59 UTC, JobsonMarinho commented on minecraft_servers/gladmc/manifest.json
> +    "web_shop": "https://loja.gladmc.com",
Fixed

2023-08-26 19:59 UTC, JobsonMarinho commented on minecraft_servers/gladmc/manifest.json
> +    "rename_to_minecraft_name": true
Fixed

2023-08-26 19:59 UTC, JobsonMarinho commented on minecraft_servers/stardix/manifest.json
> +    "rename_to_minecraft_name": true
Fixed

2023-09-19 17:04 UTC, merged