FoxxiNET
LabyMod/server-media pull request #67
Opened 2021-07-17 16:40 UTC by enno123

## Type of change

 

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2021-07-17 16:46 UTC, JakobBruening requested changes
- [ ] Please compress your images https://tinypng.com/.
- [ ] Please format your `manifest.json` as in [our example](https://store.foxxi.net).

And just a suggestion, you can add your branding to the manifest.json (because you have such a beautiful orange as your primary color) - Feel free to do that! :)
=> [Documentation](https://tinypng.com/)

2021-07-17 16:46 UTC, JakobBruening commented on minecraft_servers/foxxinet/manifest.json
> +   " direct_ip " : " Foxxi.net " ,
We prefer lowercase here.

2021-07-17 16:46 UTC, JakobBruening commented on minecraft_servers/foxxinet/manifest.json
> +     " teampeak " : " Foxxi.net "
Wer prefer lowercase here.

2021-07-17 17:10 UTC, enno123 reviewed
~ changed

2021-07-17 17:19 UTC, scrummer commented
@enno123 Pay attention: Everything, keys as well as values in your `manifest.json` have whitespaces at the beginning and end. Please remove them according to our examle [manifest.json](https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md#example-manifestjson-file)!

BR Scrummer

2021-07-17 17:20 UTC, scrummer requested changes

2021-07-17 17:20 UTC, scrummer commented on minecraft_servers/foxxinet/manifest.json
> +  ],
If you do not have any wildcards, please remove this entry.

2021-07-17 17:20 UTC, scrummer commented on minecraft_servers/foxxinet/manifest.json
> +   "primary": "#db4839",
Check indentation here (it's one instead of two required spaces)

2021-07-17 17:57 UTC, enno123 commented
- [ ] changed

2021-07-17 18:38 UTC, JakobBruening commented
No, there is still a lot broken.
Your json file is invalid. -> https://www.w3schools.com/js/js_json_syntax.asp
Please have a look at JSON syntax.

I think it would be the best to copy-paste our example `manifest.json` file and change or remove the values. So you would have a file with valid syntax, that is also formatted well!

BR, Jakob

2021-07-17 18:48 UTC, enno123 commented
I'm surprised... I copied the file. I try again

2021-07-17 18:54 UTC, enno123 commented
I hope it is now correct

2021-07-17 18:59 UTC, JakobBruening commented
Nope, my syntax error highlighter is crying 😬

<img src="https://user-images.githubusercontent.com/45363287/126047065-d8c81f2f-9b8d-4123-b4aa-3621b03c6215.png" width="400">

It's not valid json and also, there are waaay to many spaces
<img src="https://user-images.githubusercontent.com/45363287/126047075-c2e8f77f-9a41-44c8-bc0e-47b9459f591a.png" width="300">

Didn't you have have a developer in your team you could ask?

2021-07-17 19:12 UTC, enno123 commented
I will take care of it :/ Sorry for the inconvenience

2021-07-18 12:09 UTC, enno123 commented
It should be right now... hopefully

2021-07-19 16:20 UTC, merged