Add TropicalGames
LabyMod/server-media pull request #734
Opened 2023-10-14 11:07 UTC by Alessandro2012012

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2023-10-17 15:07 UTC, minepodcraft commented
i do not linke this server it is a scammer

2023-10-17 15:09 UTC, OreoBladesword commented
This server is very unfriendly to new players.
i was a new player and they disrespected me.
the co owner laify is the biggest problem!

2023-10-31 11:09 UTC, DoJapHD requested changes

2023-10-31 11:09 UTC, DoJapHD commented on minecraft_servers/TropicalGames/manifest.json
> +  "server_name": "TropicalGames",
server_name has to be lowercase (folder name too!)

2023-10-31 11:09 UTC, DoJapHD commented on minecraft_servers/TropicalGames/manifest.json
> +    "web_shop": "https://TropicalGames.de/store",
/store leads to 404

2023-10-31 11:09 UTC, DoJapHD commented on minecraft_servers/TropicalGames/manifest.json
> +     "premium.TropicalGames.de",
Redundant, %.tropicalgames already implements premium.tropicalgames

2023-10-31 11:09 UTC, DoJapHD commented on minecraft_servers/TropicalGames/manifest.json
> +  "direct_ip": "TropicalGames.de",
IP please in lowercase (also in wildcards)

2023-11-11 19:23 UTC, DoJapHD commented
Didn't answer, reopen if still needed

2023-11-11 19:23 UTC, closed without merging