Update manifest.json
LabyMod/server-media pull request #746
Opened 2023-10-28 08:53 UTC by narwhql

Changed wildcard and added tiktok

## Type of change

- [ ] Add new directory for a server
- [X] Update directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2023-10-31 10:58 UTC, JakobBruening requested changes

2023-10-31 10:58 UTC, JakobBruening commented on minecraft_servers/nektax/manifest.json
> +        "premium.nektax.net",
You can remove both, as "%.nektax.net" includes the wildcards.

2023-11-01 21:35 UTC, DoJapHD requested changes

2023-11-01 21:35 UTC, DoJapHD commented on minecraft_servers/nektax/manifest.json
>          "web_support": "https://discord.gg/zY7X4rVWEb",
web_support can't be Discord, link to FAQ; if non-existent, remove

2023-11-01 21:41 UTC, narwhql commented
Removed, strange that I had added it a while ago and it was accepted...
Anyway, should be good now 👍🏻

2023-11-01 21:59 UTC, DoJapHD commented
> Removed, strange that I had added it a while ago and it was accepted... Anyway, should be good now 👍🏻

Probably just overlooked

2023-11-01 21:59 UTC, DoJapHD approved these changes

2023-11-01 22:00 UTC, merged