Crystopia Server Update and Fixes
LabyMod/server-media pull request #766
Opened 2023-11-03 14:07 UTC by tnsjesper

## Type of change

- [ ] Add new directory for a server
- [x] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2023-11-03 15:51 UTC, DoJapHD requested changes

2023-11-03 15:51 UTC, DoJapHD commented on minecraft_servers/crystopia/background.png
Compress image

2023-11-03 15:51 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +    "web": "https://crystopia.net",
Website not reachable

2023-11-03 15:51 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +    "web_shop": "https://shop.crystopia.net",
Website not reachable

2023-11-03 15:51 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +    "web_support": "https://crystopia.net/wiki",
Website not reachable

2023-11-03 15:51 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +  "yt_trailer": "https://www.youtube.com/watch?v=Gwa4PAA6YC8"
Change to embed id

2023-11-03 17:42 UTC, tnsjesper commented on minecraft_servers/crystopia/manifest.json
> +    "web": "https://crystopia.net",
Yes i have

2023-11-03 17:58 UTC, tnsjesper commented on minecraft_servers/crystopia/manifest.json
> +    "web_shop": "https://shop.crystopia.net",
now
... i have fix it

2023-11-04 13:09 UTC, DoJapHD requested changes

2023-11-04 13:09 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +    "web": "https://crystopia.net",
Still not reachable

2023-11-04 13:09 UTC, DoJapHD commented on minecraft_servers/crystopia/manifest.json
> +    "web_shop": "https://shop.crystopia.net",
Nope

2023-11-14 18:34 UTC, DoJapHD commented
No changes made; Reopen PR if still needed

2023-11-14 18:34 UTC, closed without merging