s
LabyMod/server-media pull request #813
Opened 2023-11-19 00:49 UTC by sheduxdev

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2023-11-20 11:42 UTC, DoJapHD requested changes

2023-11-20 11:42 UTC, DoJapHD commented on minecraft_servers/sheduxdev/manifest.json
> +    "web": "https://sheduxdev.tech",
Cannot reach website

2023-11-30 15:51 UTC, DoJapHD commented
Did not change requested things; reopen PR if still needed

2023-11-30 15:51 UTC, closed without merging

2023-11-30 15:55 UTC, sheduxdev commented
The hosting I am using is currently under maintenance and I will activate it again when it opens.