Add files via upload
LabyMod/server-media pull request #818
Opened 2023-11-21 00:31 UTC by Novelnia

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2023-11-21 12:22 UTC, DoJapHD requested changes

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/background.png
Compress image

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/background@2x.png
Compress image

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/manifest.json
> +    "web_shop": "https://shop.novelnia.net",
Cannot reach shop

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/manifest.json
> +    "BedWars": {
JSON conventions, key has to be lowercase

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/manifest.json
> +    "SkyWars": {
JSON conventions, key has to be lowercase

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/manifest.json
> +    "TryJump": {
JSON conventions, key has to be lowercase

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/manifest.json
> +    "Target": {
JSON conventions, key has to be lowercase

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/manifest.json
> +    "Community": {
JSON conventions, key has to be lowercase

2023-11-21 12:22 UTC, DoJapHD commented on minecraft_servers/novelnia/manifest.json
> +    "rename_to_minecraft_name": true
Reserved for partners, change to false

2023-11-22 22:38 UTC, Novelnia commented
I've made all the requested changes to the pull request. Could someone please review the updates?

2023-11-23 13:40 UTC, DoJapHD approved these changes

2023-11-23 13:40 UTC, merged