Added Files
LabyMod/server-media pull request #823
Opened 2023-11-25 22:56 UTC by byPixelTV

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2023-11-25 23:51 UTC, DoJapHD requested changes

2023-11-25 23:51 UTC, DoJapHD commented on minecraft_servers/horizonlegacy/manifest.json
> +        "web": "https://horizonlegacy.net",
Website has invalid SSL Certificate + shows 403 error

2023-11-26 00:20 UTC, byPixelTV commented
> _Just as an information_: Your server horizonlegacy.net **could be offline**. In general, we only accept pull requests from servers, **that are online**. Please change this, otherwise we cannot review your server correctly and have to deny the pull request.
> 
> If your server is currently online, then our api returned a wrong status, we will have a look at it :)
> 
> Reference: [API URL (https://api.mcsrvstat.us/2/horizonlegacy.net)](https://api.mcsrvstat.us/2/horizonlegacy.net)

The server was offline because our hoster migrated the server to another node!

2023-11-26 12:47 UTC, DoJapHD approved these changes

2023-11-26 12:47 UTC, merged