Add TeslaNetwork
LabyMod/server-media pull request #868
Opened 2023-12-21 10:55 UTC by InvalidTeslaa

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments
[TeslaNetwork.zip](https://github.com/LabyMod/server-media/files/13740494/TeslaNetwork.zip)

2023-12-21 11:05 UTC, InvalidTeslaa commented
[teslanetwork.zip](https://github.com/LabyMod/server-media/files/13740575/teslanetwork.zip)

2023-12-21 20:49 UTC, maaaathis commented
- Invalid file type 'GIF454' for file: minecraft_servers/teslanetwork/icon.png
- Invalid icon size! Size is 512x512px, must be 256x256px: minecraft_servers/teslanetwork/icon.png
- Invalid file type 'GIF224' for file: minecraft_servers/teslanetwork/icon@2x.png
- Invalid hDPI icon size! Size is 256x256px, must be 512x512px: minecraft_servers/teslanetwork/icon@2x.png

2023-12-24 18:33 UTC, InvalidTeslaa commented
![icon@2x](https://github.com/LabyMod/server-media/assets/81645496/a6f9851c-f124-404d-bbc5-2c358f98cd0d)
![icon](https://github.com/LabyMod/server-media/assets/81645496/3d9dfbf4-2c12-4e83-8c6e-a7664d87fea0)

2023-12-24 18:49 UTC, maaaathis commented
> Changed the Icon
> 
> ![icon@2x](https://private-user-images.githubusercontent.com/81645496/292685231-a6f9851c-f124-404d-bbc5-2c358f98cd0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzEtYTZmOTg1MWMtZjEyNC00MDRkLWJiYzUtMmMzNThmOThjZDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NTViNmVkN2RjZDcwNWM0MmNkZDJmNmZiZmY0MTY2ZDQ0ZTcwZDhlYmRiNWY3YTYzNDViZTc5MjEwYmIwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10Zgi0ptGf_Uf_ZgHjSiroUv4e7tGeHiOImWMvhTHH0) ![icon](https://private-user-images.githubusercontent.com/81645496/292685232-3d9dfbf4-2c12-4e83-8c6e-a7664d87fea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzItM2Q5ZGZiZjQtMmMxMi00ZTgzLThjNmUtYTc2NjRkODdmZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjVhZTNiZjczNDUyMGVlZGFiYzM3OWRiNDNkMTUxODU3YjEyYzVlM2IzMmZjMjIyNWIwZDViZTU2ZTViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlDEBu-7Yxs5m_P0HRsdX2tbfiTMlsdpa4TouEmPfj4)

You need to make a commit to your branch to update the icons in the pull request @InvalidTeslaa.

2023-12-25 12:34 UTC, InvalidTeslaa commented
> > Changed the Icon
> > ![icon@2x](https://private-user-images.githubusercontent.com/81645496/292685231-a6f9851c-f124-404d-bbc5-2c358f98cd0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzEtYTZmOTg1MWMtZjEyNC00MDRkLWJiYzUtMmMzNThmOThjZDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NTViNmVkN2RjZDcwNWM0MmNkZDJmNmZiZmY0MTY2ZDQ0ZTcwZDhlYmRiNWY3YTYzNDViZTc5MjEwYmIwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10Zgi0ptGf_Uf_ZgHjSiroUv4e7tGeHiOImWMvhTHH0) ![icon](https://private-user-images.githubusercontent.com/81645496/292685232-3d9dfbf4-2c12-4e83-8c6e-a7664d87fea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzItM2Q5ZGZiZjQtMmMxMi00ZTgzLThjNmUtYTc2NjRkODdmZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjVhZTNiZjczNDUyMGVlZGFiYzM3OWRiNDNkMTUxODU3YjEyYzVlM2IzMmZjMjIyNWIwZDViZTU2ZTViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlDEBu-7Yxs5m_P0HRsdX2tbfiTMlsdpa4TouEmPfj4)
> 
> You need to make a commit to your branch to update the icons in the pull request @InvalidTeslaa.

How i do that? Im not very familiar with GitHub

2023-12-26 17:02 UTC, maaaathis commented
> > > Changed the Icon
> > > ![icon@2x](https://private-user-images.githubusercontent.com/81645496/292685231-a6f9851c-f124-404d-bbc5-2c358f98cd0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzEtYTZmOTg1MWMtZjEyNC00MDRkLWJiYzUtMmMzNThmOThjZDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NTViNmVkN2RjZDcwNWM0MmNkZDJmNmZiZmY0MTY2ZDQ0ZTcwZDhlYmRiNWY3YTYzNDViZTc5MjEwYmIwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10Zgi0ptGf_Uf_ZgHjSiroUv4e7tGeHiOImWMvhTHH0) ![icon](https://private-user-images.githubusercontent.com/81645496/292685232-3d9dfbf4-2c12-4e83-8c6e-a7664d87fea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzItM2Q5ZGZiZjQtMmMxMi00ZTgzLThjNmUtYTc2NjRkODdmZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjVhZTNiZjczNDUyMGVlZGFiYzM3OWRiNDNkMTUxODU3YjEyYzVlM2IzMmZjMjIyNWIwZDViZTU2ZTViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlDEBu-7Yxs5m_P0HRsdX2tbfiTMlsdpa4TouEmPfj4)
> > 
> > 
> > You need to make a commit to your branch to update the icons in the pull request @InvalidTeslaa.
> 
> How i do that? Im not very familiar with GitHub

You remove the current icons here and upload the new ones: https://github.com/InvalidTeslaa/server-media/tree/master/minecraft_servers/teslanetwork
The pull request will be updated automatically.

2023-12-26 17:16 UTC, InvalidTeslaa commented
> > > > Changed the Icon
> > > > ![icon@2x](https://private-user-images.githubusercontent.com/81645496/292685231-a6f9851c-f124-404d-bbc5-2c358f98cd0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzEtYTZmOTg1MWMtZjEyNC00MDRkLWJiYzUtMmMzNThmOThjZDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NTViNmVkN2RjZDcwNWM0MmNkZDJmNmZiZmY0MTY2ZDQ0ZTcwZDhlYmRiNWY3YTYzNDViZTc5MjEwYmIwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10Zgi0ptGf_Uf_ZgHjSiroUv4e7tGeHiOImWMvhTHH0) ![icon](https://private-user-images.githubusercontent.com/81645496/292685232-3d9dfbf4-2c12-4e83-8c6e-a7664d87fea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NDM5ODUsIm5iZiI6MTcwMzQ0MzY4NSwicGF0aCI6Ii84MTY0NTQ5Ni8yOTI2ODUyMzItM2Q5ZGZiZjQtMmMxMi00ZTgzLThjNmUtYTc2NjRkODdmZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE4NDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjVhZTNiZjczNDUyMGVlZGFiYzM3OWRiNDNkMTUxODU3YjEyYzVlM2IzMmZjMjIyNWIwZDViZTU2ZTViY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlDEBu-7Yxs5m_P0HRsdX2tbfiTMlsdpa4TouEmPfj4)
> > > 
> > > 
> > > You need to make a commit to your branch to update the icons in the pull request @InvalidTeslaa.
> > 
> > 
> > How i do that? Im not very familiar with GitHub
> 
> You remove the current icons here and upload the new ones: https://github.com/InvalidTeslaa/server-media/tree/master/minecraft_servers/teslanetwork The pull request will be updated automatically.

Done, have reuploaded the new ones

2023-12-26 17:23 UTC, maaaathis commented
The manifest has to be a json file.

2023-12-26 17:28 UTC, maaaathis commented
Is your website online?
![image](https://github.com/LabyMod/server-media/assets/37186532/ccb0628b-74dd-44db-b8fc-3788b5f7922d)

2023-12-26 17:33 UTC, InvalidTeslaa commented
> Is your website online? ![image](https://private-user-images.githubusercontent.com/37186532/292900649-ccb0628b-74dd-44db-b8fc-3788b5f7922d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTIwMDQsIm5iZiI6MTcwMzYxMTcwNCwicGF0aCI6Ii8zNzE4NjUzMi8yOTI5MDA2NDktY2NiMDYyOGItNzRkZC00NGRiLWI4ZmMtMzc4OGI1Zjc5MjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MjgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMmQyZTcxYjFlMWE0ZTRiNDNmZTU1MDFmOGE4MGE2OTVmYmJiYjI3MWMzZWU5MjU3M2I3YTFiZWM0MjgyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Gv-TjkaH3OqYOZmYcR3l9ghklJbFP4oz4zPNSkRplY)

Website hosting is expired and during issues with paypal im currently not able to renew it, maybe in a few days its online again

2023-12-26 17:37 UTC, InvalidTeslaa commented
great now nothing works anymore, images and manifest are booth invalid

2023-12-26 17:45 UTC, maaaathis commented
> great now nothing works anymore, images and manifest are booth invalid

Your manifest is not a valid json file. You need to close the "gamesmodes" object and remove the comma after "social"."discord".
Try https://jsonlint.com for validation of your manifest.

2023-12-26 17:56 UTC, InvalidTeslaa commented
> > great now nothing works anymore, images and manifest are booth invalid
> 
> Your manifest is not a valid json file. You need to close the "gamesmodes" object and remove the comma after "social"."discord". Try https://jsonlint.com for a validation of your manifest.

Updated

2023-12-26 17:58 UTC, maaaathis commented
> > > great now nothing works anymore, images and manifest are booth invalid
> > 
> > 
> > Your manifest is not a valid json file. You need to close the "gamesmodes" object and remove the comma after "social"."discord". Try https://jsonlint.com for a validation of your manifest.
> 
> Updated

Thats my corrected version **with your gamesmodes**, feel free to update.
```
{
    "server_name": "teslanetwork",
    "nice_name": "TeslaNetwork",
    "direct_ip": "mc.teslaa.net",
    "supported_languages": [
        "en",
        "de"
    ],
    "social": {
        "web": "https://teslaa.net",
        "web_support": "https://teslaa.net/support",
        "discord": "https://discord.gg/teslaa"
    },
    "gamemodes": {
        "citybuild": {
            "name": "CityBuild",
            "color": "#FFA500",
            "versions": "1.17<*"
        },
        "survival": {
            "name": "Survival",
            "color": "#ADD8E6",
            "versions": "1.17<*"
        }
    }
}
```

2023-12-26 18:00 UTC, InvalidTeslaa commented
Ah i see, i forgot to add a "}", changed

> > > > great now nothing works anymore, images and manifest are booth invalid
> > > 
> > > 
> > > Your manifest is not a valid json file. You need to close the "gamesmodes" object and remove the comma after "social"."discord". Try https://jsonlint.com for a validation of your manifest.
> > 
> > 
> > Updated
> 
> Thats my corrected version **with your gamesmodes**, feel free to update.
> 
> ```
> {
>     "server_name": "teslanetwork",
>     "nice_name": "TeslaNetwork",
>     "direct_ip": "mc.teslaa.net",
>     "supported_languages": [
>         "en",
>         "de"
>     ],
>     "social": {
>         "web": "https://teslaa.net",
>         "web_support": "https://teslaa.net/support",
>         "discord": "https://discord.gg/teslaa"
>     },
>     "gamemodes": {
>         "citybuild": {
>             "name": "CityBuild",
>             "color": "#FFA500",
>             "versions": "1.17<*"
>         },
>         "survival": {
>             "name": "Survival",
>             "color": "#ADD8E6",
>             "versions": "1.17<*"
>         }
>     }
> }
> ```

2023-12-26 18:00 UTC, toohard2explain commented
The logo is copyrighted and not yours, i don't think you're allowed to use that image.

2023-12-26 18:02 UTC, InvalidTeslaa commented
> The logo is copyrighted and not yours, i don't think you're allowed to use that image.
I just made a screenshot of an gif from tenor 🤔

2023-12-26 18:06 UTC, toohard2explain commented
> > > The logo is copyrighted and not yours, i don't think you're allowed to use that image.
> > I just made a screenshot of an gif from tenor 🤔

I dont think that this makes it better tbh... you should make or buy your own serverlogo (maybe on fiverr)

2023-12-26 18:14 UTC, InvalidTeslaa commented
What about this one? 🤔

2023-12-26 18:16 UTC, toohard2explain commented
> What about this one? 🤔

you can't just take tesla's logo and recolor it, its a brandmark that is protected. you have to make something completely new when you want to be legal

2023-12-26 18:25 UTC, maaaathis commented
> great now nothing works anymore, images and manifest are booth invalid

I don't know the exact reason why the image validation pipeline fails, but try compressing your backgroundfiles (https://tinypng.com/) and make sure they are the right size: https://github.com/LabyMod/server-media/blob/master/docs/Files.md

2023-12-26 18:38 UTC, InvalidTeslaa commented
> > What about this one? 🤔
> 
> you can't just take tesla's logo and recolor it, its a brandmark that is protected. you have to make something completely new when you want to be legal

Now i make a new one, this will work until we have a new one which will be permanently

2023-12-26 18:41 UTC, toohard2explain commented
> > > What about this one? 🤔
> > 
> > 
> > you can't just take tesla's logo and recolor it, its a brandmark that is protected. you have to make something completely new when you want to be legal
> 
> Now it have a new one, this will work until we have a new one which will be permanently

you did not even remove the old one and the wordmark is also copyrighted, you cannot just use it, i dont even know if you're allowed to use the name at all

2023-12-26 18:42 UTC, InvalidTeslaa commented
Which old one, they got overwritten

2023-12-26 18:43 UTC, toohard2explain commented
> Which old one, they got overwritten

no you created `icon@2 (2)`

2023-12-26 18:46 UTC, InvalidTeslaa commented
> > Which old one, they got overwritten
> 
> no you created `icon@2 (2)`

Oh, bad. My fault

2023-12-27 17:15 UTC, toohard2explain commented
you still can't use the tesla wordmark, its also protected. you have to make something completely new..

2024-01-07 20:04 UTC, InvalidTeslaa commented
So we changed our Servername so is it now possible to get this resolved?

2024-01-07 20:15 UTC, maaaathis commented
> So we changed our Servername so is it now possible to get this resolved?

Compress your images and add a icon.png. See reference here: https://github.com/LabyMod/server-media/blob/master/docs/Files.md#filestructure

2024-01-07 20:35 UTC, InvalidTeslaa commented
And yeah the server is not reachable due to cloudflare checks

https://cdn.teslaa.net/2024/01/07/88b2b3d1-4039-4793-be16-fd5b7204eec5.png

2024-01-07 20:37 UTC, InvalidTeslaa commented
All is done

2024-01-07 21:10 UTC, DoJapHD requested changes

2024-01-07 21:10 UTC, DoJapHD commented on minecraft_servers/letsgrief/background.png
Compress image

2024-01-07 21:10 UTC, DoJapHD commented on minecraft_servers/letsgrief/background@2x.png
Compress image

2024-01-07 21:10 UTC, DoJapHD commented on minecraft_servers/letsgrief/manifest.json
> +        "web": "https://letsgrief.net",
Website not reachable; remove if non-existent

2024-01-07 21:10 UTC, DoJapHD commented on minecraft_servers/letsgrief/manifest.json
> +        "web_support": "https://letsgrief.net/support",
Website not reachable; remove if non-existent

2024-01-07 21:10 UTC, DoJapHD commented
Server in general not reachable; Reopen once reachable again

2024-01-07 21:10 UTC, closed without merging

2024-01-08 20:38 UTC, InvalidTeslaa commented
Domain now working, Server reachable same as Website

2024-01-08 20:44 UTC, InvalidTeslaa commented
Unable to reopen request so i have to make a new one