suchtify
LabyMod/server-media pull request #881
Opened 2023-12-30 00:05 UTC by Vinnipapi

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2023-12-31 12:05 UTC, toohard2explain commented
please rename your pull request

2023-12-31 12:08 UTC, toohard2explain commented
also, is the server even accessible?

![image](https://github.com/LabyMod/server-media/assets/78054244/78d7efc3-9b53-4001-9c37-b514edd4dd38)

2023-12-31 12:46 UTC, Vinnipapi commented
> also, is the server even accessible?
> 
> ![image](https://private-user-images.githubusercontent.com/78054244/293504573-78d7efc3-9b53-4001-9c37-b514edd4dd38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjY4NDQsIm5iZiI6MTcwNDAyNjU0NCwicGF0aCI6Ii83ODA1NDI0NC8yOTM1MDQ1NzMtNzhkN2VmYzMtOWI1My00MDAxLTljMzctYjUxNGVkZDRkZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDEyNDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxOWM4YjM5M2FlNjNjYzc1MzJiOGRjNjE3ZTQ0OGJhMmQwMTZlMzlkNTA3MWQ5NDc5OTg4Y2Q0MTYyYzNhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x68xdseVMA2ilgCi7QIW2EV-bbICG9DOusSw7t0VFDo)

Yes at the moment we are undergoing maintenance and due to holiday break we can not work on our network so basicly it will be reaccessable in early 2024

2023-12-31 12:46 UTC, Vinnipapi commented
> please rename your pull request

To what? I renamed it to the current server ip if its alright!

2024-01-06 18:35 UTC, DoJapHD requested changes

2024-01-06 18:35 UTC, DoJapHD commented on minecraft_servers/suchtify/manifest.json
> +    "web": "https://suchtify.de",
Website not reachable

2024-01-06 18:35 UTC, DoJapHD commented on minecraft_servers/suchtify/manifest.json
> +    "web_shop": "https://suchtify.de/shop",
Website not reachable

2024-01-06 18:35 UTC, DoJapHD commented on minecraft_servers/suchtify/manifest.json
> +    "web_support": "https://wiki.suchtify.de",
Website not reachable

2024-01-06 18:35 UTC, DoJapHD commented on minecraft_servers/suchtify/manifest.json
> +      "url": "https://suchtify.de",
Doesn't make sense here, remove

2024-01-06 18:36 UTC, closed without merging

2024-01-06 18:36 UTC, DoJapHD commented
Server in general not reachable; reopen PR once reachable