Add Mellxy to Server dircetory
LabyMod/server-media pull request #890
Opened 2024-01-05 12:17 UTC by timzocker11

## Type of change

- [x] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [x] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [x] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [x] I have created the manifest.json with the required values

## Further comments

2024-01-06 18:45 UTC, DoJapHD requested changes

2024-01-06 18:45 UTC, DoJapHD commented on minecraft_servers/mellxy/background.png
Compress image

2024-01-06 18:45 UTC, DoJapHD commented on minecraft_servers/mellxy/background@2x.png
Compress image

2024-01-06 19:30 UTC, timzocker11 commented on minecraft_servers/mellxy/background@2x.png
We have deleted the pictures for now, but they may be added later.

2024-01-07 12:06 UTC, DoJapHD approved these changes

2024-01-07 12:06 UTC, merged