Add AscalterDE Server
LabyMod/server-media pull request #908
Opened 2024-01-17 21:19 UTC by realTiim

## Type of change

- [X] Add new directory for a server

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-01-17 21:26 UTC, realTiim commented
The commit is ready to be merged

2024-01-18 16:52 UTC, DoJapHD requested changes

2024-01-18 16:52 UTC, DoJapHD commented on minecraft_servers/ascalter/manifest.json
> +      "web_support": "https://forum.ascalter.de/forum/index.php?board/4",
Web support cannot be forum, add FAQ or contact form

2024-01-18 21:28 UTC, DoJapHD approved these changes

2024-01-18 21:28 UTC, merged