Add BaxNetzwerk Server-Media Data
LabyMod/server-media pull request #933
Opened 2024-01-28 17:20 UTC by Ente3

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-01-28 17:26 UTC, maaaathis requested changes

2024-01-28 17:26 UTC, maaaathis commented on minecraft_servers/baxnetzwerk/Manifest.json
file has to be `manifest.json`

2024-01-28 17:26 UTC, maaaathis commented on minecraft_servers/baxnetzwerk/Manifest.json
> +      "web_support": "https://BaxNetzwerk.de/dev",
`web_support` cannot be a development progress bar

2024-01-28 17:28 UTC, maaaathis commented
Server is currently not open to public 
![image](https://github.com/LabyMod/server-media/assets/37186532/d2ff4f78-f1ac-463f-bce1-856a0c8c4862)

2024-02-02 22:31 UTC, DoJapHD commented
PR inactive

2024-02-02 22:31 UTC, closed without merging