Update manifest.json
LabyMod/server-media pull request #937
Opened 2024-01-29 09:22 UTC by ZoruaFox

## Type of change

- [ ] Add new directory for a server
- [X] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-01-29 11:39 UTC, maaaathis requested changes

2024-01-29 11:39 UTC, maaaathis commented on minecraft_servers/ysserver/manifest.json
> +    "mc.zorua.top"
That's not a valid wildcard.

2024-01-31 01:34 UTC, ZoruaFox commented
> `%.mc.zorua.top` doesn't seem to be a real wildcard: ![image](https://private-user-images.githubusercontent.com/37186532/300849848-31ef83c1-89d5-49ab-b2f2-33dfc5ee666e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NjUwNTQsIm5iZiI6MTcwNjY2NDc1NCwicGF0aCI6Ii8zNzE4NjUzMi8zMDA4NDk4NDgtMzFlZjgzYzEtODlkNS00OWFiLWIyZjItMzNkZmM1ZWU2NjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAxMzIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOGIyNzg1ZTBkYWQyN2IxYmFkNmQ5ZmU0MGI0N2VkYmEyNDdjNWI4ZDJkMDA3ODA5N2ZiZTQ3NDljZjYyYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w5K162EZe9dYuUoM5Coz_i1kZxyzFcsKhYWYoeG0Lq8)
> 
> If only `mc.zorua.top` resolves to your server and not every subdomain of `mc.zorua.top`, that isn't a valid wildcard.

Thanks for the suggestion, the code has been removed.

2024-01-31 06:55 UTC, maaaathis approved these changes
Thanks, looks good!

2024-02-02 22:31 UTC, DoJapHD approved these changes

2024-02-02 22:31 UTC, merged