Add Ranked Network / Changed manifest.json
LabyMod/server-media pull request #942
Opened 2024-01-31 20:24 UTC by JustReddy7397

## Type of change

- [ ] Update directory of a server

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments
Hopefully **it** works now :).

2024-01-31 20:59 UTC, maaaathis requested changes

2024-01-31 20:59 UTC, maaaathis commented on minecraft_servers/RankedNetwork/background.png
compress

2024-01-31 20:59 UTC, maaaathis commented on minecraft_servers/RankedNetwork/background@2x.png
compress

2024-02-09 20:41 UTC, DoJapHD commented
PR inactive

2024-02-09 20:41 UTC, closed without merging