NorthSoft
LabyMod/server-media pull request #975
Opened 2024-02-17 12:31 UTC by HyperGaming99

My Minecraft Server

2024-02-17 13:38 UTC, maaaathis requested changes

2024-02-17 13:38 UTC, maaaathis commented on minecraft_servers/northsoft/background.png
Compress this file

2024-02-17 13:38 UTC, maaaathis commented on minecraft_servers/northsoft/background@2x.png
Compress this file

2024-02-17 13:38 UTC, maaaathis commented on minecraft_servers/northsoft/manifest.json
> +      "discord": "https://dsc.gg/northsoft",
Custom links are reserved for partners only; use a normal discord.gg/[YOUR-INVITE] link

2024-02-18 01:11 UTC, HyperGaming99 commented
Updatet

2024-02-18 14:32 UTC, DoJapHD approved these changes

2024-02-18 14:33 UTC, merged

2024-02-19 13:51 UTC, HyperGaming99 commented
Thanks vor Merge

2024-06-18 17:21 UTC, HyperGaming99 commented
Can you remove Northsoft from LabyMod