Update manifest.json
LabyMod/server-media pull request #977
Opened 2024-02-18 16:15 UTC by minepodcraft

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-02-18 17:23 UTC, DoJapHD requested changes

2024-02-18 17:23 UTC, DoJapHD commented on minecraft_servers/onthepixel/manifest.json
>      "kitpvp": {
Change key if you change its purpose

2024-02-18 17:23 UTC, DoJapHD commented on minecraft_servers/onthepixel/manifest.json
>      "tntrun":{
Same here

2024-02-18 17:23 UTC, DoJapHD commented on minecraft_servers/onthepixel/manifest.json
>      "bridging":{
Same here

2024-02-18 19:58 UTC, DoJapHD commented
Why is the server under maintenance?

2024-02-19 15:56 UTC, minepodcraft commented
> Why is the server under maintenance?

we are rebuilding the server

2024-02-19 19:35 UTC, DoJapHD commented
Oh well, normally only released servers are getting added to the repository but as it's already added, I'll make an exception

2024-02-19 19:35 UTC, DoJapHD approved these changes

2024-02-19 19:35 UTC, merged