Add Flame
LabyMod/server-media pull request #990
Opened 2024-02-26 22:41 UTC by thekillerregs

## Type of change

- [X] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [X] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [X] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [X] I have created the manifest.json with the required values

## Further comments

2024-02-26 23:14 UTC, maaaathis requested changes

2024-02-26 23:14 UTC, maaaathis commented on minecraft_servers/flame/background.png
Compress this file

2024-02-26 23:14 UTC, maaaathis commented on minecraft_servers/flame/background@2x.png
Compress this file

2024-02-26 23:23 UTC, thekillerregs commented on minecraft_servers/flame/background.png
Done!

2024-02-26 23:23 UTC, thekillerregs commented on minecraft_servers/flame/background@2x.png
Done!

2024-02-27 19:27 UTC, DoJapHD approved these changes

2024-02-27 19:27 UTC, merged