revengenetwork
LabyMod/server-media pull request #997
Opened 2024-03-01 03:47 UTC by G4shetita

## Type of change

- [ ] Add new directory for a server
- [ ] Update directory of a server
- [ ] Remove directory of a server
- [ ] Documentation Update

## Checklist

- [ ] I have read the [README](https://github.com/LabyMod/server-media/blob/master/README.md) doc
- [ ] I have compressed the images appropriately (e.g. on https://tinypng.com)
- [ ] I have created the manifest.json with the required values

## Further comments

2024-03-01 06:42 UTC, maaaathis requested changes

2024-03-01 06:42 UTC, maaaathis commented on minecraft_servers/revengenetwork/background.png
Compress this file

2024-03-01 13:17 UTC, G4shetita commented on minecraft_servers/revengenetwork/background.png
compresed

2024-03-01 21:08 UTC, DoJapHD requested changes

2024-03-01 21:08 UTC, DoJapHD commented on minecraft_servers/revengenetwork/manifest.json
> +  "direct_ip": "RevengeNetwork.es",
Lowercase IP

2024-03-01 21:08 UTC, DoJapHD commented on minecraft_servers/revengenetwork/manifest.json
> +    "%.RevengeNetwork.es"
Lowercase IP

2024-03-01 21:16 UTC, G4shetita commented on minecraft_servers/revengenetwork/manifest.json
> +    "%.RevengeNetwork.es"
changed

2024-03-02 11:37 UTC, DoJapHD approved these changes

2024-03-02 11:38 UTC, merged